package ar.TpDisenio2019.Model;
// Generated 5/02/2020 07:38:19 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aniodevehiculo generated by hbm2java
 */
@Entity
@Table(name = "aniodevehiculo", catalog = "dbelaseguradov4")
public class Aniodevehiculo implements java.io.Serializable {

	private Integer idAnioDeVehiculo;
	private Date anio;
	private Set<Aniomodelo> aniomodelos = new HashSet<Aniomodelo>(0);

	public Aniodevehiculo() {
	}

	public Aniodevehiculo(Date anio, Set<Aniomodelo> aniomodelos) {
		this.anio = anio;
		this.aniomodelos = aniomodelos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAnioDeVehiculo", unique = true, nullable = false)
	public Integer getIdAnioDeVehiculo() {
		return this.idAnioDeVehiculo;
	}

	public void setIdAnioDeVehiculo(Integer idAnioDeVehiculo) {
		this.idAnioDeVehiculo = idAnioDeVehiculo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anio", length = 0)
	public Date getAnio() {
		return this.anio;
	}

	public void setAnio(Date anio) {
		this.anio = anio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aniodevehiculo")
	public Set<Aniomodelo> getAniomodelos() {
		return this.aniomodelos;
	}

	public void setAniomodelos(Set<Aniomodelo> aniomodelos) {
		this.aniomodelos = aniomodelos;
	}

}
