package ar.TpDisenio2019.Mapping;
// Generated 3/12/2019 08:29:13 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cuota generated by hbm2java
 */
@Entity
@Table(name = "cuota", catalog = "dbelaseguradov4")
public class Cuota  {

	private int idCuotas;
	private Integer idRecibo;
	private Integer cuotasPagas;
	private Date vencimiento;
	private Float valorOriginal;
	private Float valorPorMora;
	private Float valorTotalaPagar;
	private Float bonificacion;
	private Float recargoPorMora;

	public Cuota() {
	}

	public Cuota(int idCuotas) {
		this.idCuotas = idCuotas;
	}

	public Cuota(int idCuotas, Integer idRecibo, Integer cuotasPagas, Date vencimiento, Float valorOriginal,
			Float valorPorMora, Float valorTotalaPagar, Float bonificacion, Float recargoPorMora) {
		this.idCuotas = idCuotas;
		this.idRecibo = idRecibo;
		this.cuotasPagas = cuotasPagas;
		this.vencimiento = vencimiento;
		this.valorOriginal = valorOriginal;
		this.valorPorMora = valorPorMora;
		this.valorTotalaPagar = valorTotalaPagar;
		this.bonificacion = bonificacion;
		this.recargoPorMora = recargoPorMora;
	}

	@Id

	@Column(name = "idCuotas", unique = true, nullable = false)
	public int getIdCuotas() {
		return this.idCuotas;
	}

	public void setIdCuotas(int idCuotas) {
		this.idCuotas = idCuotas;
	}

	@Column(name = "idRecibo")
	public Integer getIdRecibo() {
		return this.idRecibo;
	}

	public void setIdRecibo(Integer idRecibo) {
		this.idRecibo = idRecibo;
	}

	@Column(name = "cuotasPagas")
	public Integer getCuotasPagas() {
		return this.cuotasPagas;
	}

	public void setCuotasPagas(Integer cuotasPagas) {
		this.cuotasPagas = cuotasPagas;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "vencimiento", length = 10)
	public Date getVencimiento() {
		return this.vencimiento;
	}

	public void setVencimiento(Date vencimiento) {
		this.vencimiento = vencimiento;
	}

	@Column(name = "valorOriginal", precision = 12, scale = 0)
	public Float getValorOriginal() {
		return this.valorOriginal;
	}

	public void setValorOriginal(Float valorOriginal) {
		this.valorOriginal = valorOriginal;
	}

	@Column(name = "valorPorMora", precision = 12, scale = 0)
	public Float getValorPorMora() {
		return this.valorPorMora;
	}

	public void setValorPorMora(Float valorPorMora) {
		this.valorPorMora = valorPorMora;
	}

	@Column(name = "valorTotalaPagar", precision = 12, scale = 0)
	public Float getValorTotalaPagar() {
		return this.valorTotalaPagar;
	}

	public void setValorTotalaPagar(Float valorTotalaPagar) {
		this.valorTotalaPagar = valorTotalaPagar;
	}

	@Column(name = "bonificacion", precision = 12, scale = 0)
	public Float getBonificacion() {
		return this.bonificacion;
	}

	public void setBonificacion(Float bonificacion) {
		this.bonificacion = bonificacion;
	}

	@Column(name = "recargoPorMora", precision = 12, scale = 0)
	public Float getRecargoPorMora() {
		return this.recargoPorMora;
	}

	public void setRecargoPorMora(Float recargoPorMora) {
		this.recargoPorMora = recargoPorMora;
	}

}
