package ar.TpDisenio2019.Mapping;
// Generated 3/12/2019 08:29:13 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Factoresusados generated by hbm2java
 */
@Entity
@Table(name = "factoresusados", catalog = "dbelaseguradov4")
public class Factoresusados  {

	private int idFacUsados;
	private int idMedPorc;
	private Float porcentajeCobertura;
	private Float porcentajePorRiesgoDeDomicilio;
	private Float porcentajePorKm;
	private Float porcentajePorModeloVehiculo;
	private Float porcentajePorMedidasDeSeguridad;
	private Float porcentajePorSiniestro;
	private Float porcentajePorHijo;
	private Float importePorDescuentosPagoSemestral;
	private Float descuentoPorUnidad;
	private Float montoTotal;
	private Float prima;

	public Factoresusados() {
	}

	public Factoresusados(int idFacUsados, int idMedPorc) {
		this.idFacUsados = idFacUsados;
		this.idMedPorc = idMedPorc;
	}

	public Factoresusados(int idFacUsados, int idMedPorc, Float porcentajeCobertura,
			Float porcentajePorRiesgoDeDomicilio, Float porcentajePorKm, Float porcentajePorModeloVehiculo,
			Float porcentajePorMedidasDeSeguridad, Float porcentajePorSiniestro, Float porcentajePorHijo,
			Float importePorDescuentosPagoSemestral, Float descuentoPorUnidad, Float montoTotal, Float prima) {
		this.idFacUsados = idFacUsados;
		this.idMedPorc = idMedPorc;
		this.porcentajeCobertura = porcentajeCobertura;
		this.porcentajePorRiesgoDeDomicilio = porcentajePorRiesgoDeDomicilio;
		this.porcentajePorKm = porcentajePorKm;
		this.porcentajePorModeloVehiculo = porcentajePorModeloVehiculo;
		this.porcentajePorMedidasDeSeguridad = porcentajePorMedidasDeSeguridad;
		this.porcentajePorSiniestro = porcentajePorSiniestro;
		this.porcentajePorHijo = porcentajePorHijo;
		this.importePorDescuentosPagoSemestral = importePorDescuentosPagoSemestral;
		this.descuentoPorUnidad = descuentoPorUnidad;
		this.montoTotal = montoTotal;
		this.prima = prima;
	}

	@Id

	@Column(name = "idFacUsados", unique = true, nullable = false)
	public int getIdFacUsados() {
		return this.idFacUsados;
	}

	public void setIdFacUsados(int idFacUsados) {
		this.idFacUsados = idFacUsados;
	}

	@Column(name = "idMedPorc", nullable = false)
	public int getIdMedPorc() {
		return this.idMedPorc;
	}

	public void setIdMedPorc(int idMedPorc) {
		this.idMedPorc = idMedPorc;
	}

	@Column(name = "porcentajeCobertura", precision = 12, scale = 0)
	public Float getPorcentajeCobertura() {
		return this.porcentajeCobertura;
	}

	public void setPorcentajeCobertura(Float porcentajeCobertura) {
		this.porcentajeCobertura = porcentajeCobertura;
	}

	@Column(name = "porcentajePorRiesgoDeDomicilio", precision = 12, scale = 0)
	public Float getPorcentajePorRiesgoDeDomicilio() {
		return this.porcentajePorRiesgoDeDomicilio;
	}

	public void setPorcentajePorRiesgoDeDomicilio(Float porcentajePorRiesgoDeDomicilio) {
		this.porcentajePorRiesgoDeDomicilio = porcentajePorRiesgoDeDomicilio;
	}

	@Column(name = "porcentajePorKm", precision = 12, scale = 0)
	public Float getPorcentajePorKm() {
		return this.porcentajePorKm;
	}

	public void setPorcentajePorKm(Float porcentajePorKm) {
		this.porcentajePorKm = porcentajePorKm;
	}

	@Column(name = "porcentajePorModeloVehiculo", precision = 12, scale = 0)
	public Float getPorcentajePorModeloVehiculo() {
		return this.porcentajePorModeloVehiculo;
	}

	public void setPorcentajePorModeloVehiculo(Float porcentajePorModeloVehiculo) {
		this.porcentajePorModeloVehiculo = porcentajePorModeloVehiculo;
	}

	@Column(name = "porcentajePorMedidasDeSeguridad", precision = 12, scale = 0)
	public Float getPorcentajePorMedidasDeSeguridad() {
		return this.porcentajePorMedidasDeSeguridad;
	}

	public void setPorcentajePorMedidasDeSeguridad(Float porcentajePorMedidasDeSeguridad) {
		this.porcentajePorMedidasDeSeguridad = porcentajePorMedidasDeSeguridad;
	}

	@Column(name = "porcentajePorSiniestro", precision = 12, scale = 0)
	public Float getPorcentajePorSiniestro() {
		return this.porcentajePorSiniestro;
	}

	public void setPorcentajePorSiniestro(Float porcentajePorSiniestro) {
		this.porcentajePorSiniestro = porcentajePorSiniestro;
	}

	@Column(name = "porcentajePorHijo", precision = 12, scale = 0)
	public Float getPorcentajePorHijo() {
		return this.porcentajePorHijo;
	}

	public void setPorcentajePorHijo(Float porcentajePorHijo) {
		this.porcentajePorHijo = porcentajePorHijo;
	}

	@Column(name = "importePorDescuentosPagoSemestral", precision = 12, scale = 0)
	public Float getImportePorDescuentosPagoSemestral() {
		return this.importePorDescuentosPagoSemestral;
	}

	public void setImportePorDescuentosPagoSemestral(Float importePorDescuentosPagoSemestral) {
		this.importePorDescuentosPagoSemestral = importePorDescuentosPagoSemestral;
	}

	@Column(name = "descuentoPorUnidad", precision = 12, scale = 0)
	public Float getDescuentoPorUnidad() {
		return this.descuentoPorUnidad;
	}

	public void setDescuentoPorUnidad(Float descuentoPorUnidad) {
		this.descuentoPorUnidad = descuentoPorUnidad;
	}

	@Column(name = "montoTotal", precision = 12, scale = 0)
	public Float getMontoTotal() {
		return this.montoTotal;
	}

	public void setMontoTotal(Float montoTotal) {
		this.montoTotal = montoTotal;
	}

	@Column(name = "prima", precision = 12, scale = 0)
	public Float getPrima() {
		return this.prima;
	}

	public void setPrima(Float prima) {
		this.prima = prima;
	}

}
