package ar.TpDisenio2019.Mapping;
// Generated 3/12/2019 08:29:13 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Modificacionpoliza generated by hbm2java
 */
@Entity
@Table(name = "modificacionpoliza", catalog = "dbelaseguradov4")
public class Modificacionpoliza  {

	private int idModificacionPoliza;
	private int idVehiculo;
	private int idMedidasSeguridad;
	private int idDatosHijo;
	private int idTipoCobertura;
	private int identNroPoliza;
	private Date anio;
	private String patente;
	private String motor;
	private String chasis;
	private String nroSiniestro;
	private Integer kmPorAnio;
	private Float montoTotal;

	public Modificacionpoliza() {
	}

	public Modificacionpoliza(int idModificacionPoliza, int idVehiculo, int idMedidasSeguridad, int idDatosHijo,
			int idTipoCobertura, int identNroPoliza) {
		this.idModificacionPoliza = idModificacionPoliza;
		this.idVehiculo = idVehiculo;
		this.idMedidasSeguridad = idMedidasSeguridad;
		this.idDatosHijo = idDatosHijo;
		this.idTipoCobertura = idTipoCobertura;
		this.identNroPoliza = identNroPoliza;
	}

	public Modificacionpoliza(int idModificacionPoliza, int idVehiculo, int idMedidasSeguridad, int idDatosHijo,
			int idTipoCobertura, int identNroPoliza, Date anio, String patente, String motor, String chasis,
			String nroSiniestro, Integer kmPorAnio, Float montoTotal) {
		this.idModificacionPoliza = idModificacionPoliza;
		this.idVehiculo = idVehiculo;
		this.idMedidasSeguridad = idMedidasSeguridad;
		this.idDatosHijo = idDatosHijo;
		this.idTipoCobertura = idTipoCobertura;
		this.identNroPoliza = identNroPoliza;
		this.anio = anio;
		this.patente = patente;
		this.motor = motor;
		this.chasis = chasis;
		this.nroSiniestro = nroSiniestro;
		this.kmPorAnio = kmPorAnio;
		this.montoTotal = montoTotal;
	}

	@Id

	@Column(name = "idModificacionPoliza", unique = true, nullable = false)
	public int getIdModificacionPoliza() {
		return this.idModificacionPoliza;
	}

	public void setIdModificacionPoliza(int idModificacionPoliza) {
		this.idModificacionPoliza = idModificacionPoliza;
	}

	@Column(name = "idVehiculo", nullable = false)
	public int getIdVehiculo() {
		return this.idVehiculo;
	}

	public void setIdVehiculo(int idVehiculo) {
		this.idVehiculo = idVehiculo;
	}

	@Column(name = "idMedidasSeguridad", nullable = false)
	public int getIdMedidasSeguridad() {
		return this.idMedidasSeguridad;
	}

	public void setIdMedidasSeguridad(int idMedidasSeguridad) {
		this.idMedidasSeguridad = idMedidasSeguridad;
	}

	@Column(name = "idDatosHijo", nullable = false)
	public int getIdDatosHijo() {
		return this.idDatosHijo;
	}

	public void setIdDatosHijo(int idDatosHijo) {
		this.idDatosHijo = idDatosHijo;
	}

	@Column(name = "idTipoCobertura", nullable = false)
	public int getIdTipoCobertura() {
		return this.idTipoCobertura;
	}

	public void setIdTipoCobertura(int idTipoCobertura) {
		this.idTipoCobertura = idTipoCobertura;
	}

	@Column(name = "identNroPoliza", nullable = false)
	public int getIdentNroPoliza() {
		return this.identNroPoliza;
	}

	public void setIdentNroPoliza(int identNroPoliza) {
		this.identNroPoliza = identNroPoliza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anio", length = 0)
	public Date getAnio() {
		return this.anio;
	}

	public void setAnio(Date anio) {
		this.anio = anio;
	}

	@Column(name = "patente", length = 10)
	public String getPatente() {
		return this.patente;
	}

	public void setPatente(String patente) {
		this.patente = patente;
	}

	@Column(name = "motor", length = 20)
	public String getMotor() {
		return this.motor;
	}

	public void setMotor(String motor) {
		this.motor = motor;
	}

	@Column(name = "chasis", length = 20)
	public String getChasis() {
		return this.chasis;
	}

	public void setChasis(String chasis) {
		this.chasis = chasis;
	}

	@Column(name = "nroSiniestro", length = 10)
	public String getNroSiniestro() {
		return this.nroSiniestro;
	}

	public void setNroSiniestro(String nroSiniestro) {
		this.nroSiniestro = nroSiniestro;
	}

	@Column(name = "kmPorAnio")
	public Integer getKmPorAnio() {
		return this.kmPorAnio;
	}

	public void setKmPorAnio(Integer kmPorAnio) {
		this.kmPorAnio = kmPorAnio;
	}

	@Column(name = "montoTotal", precision = 12, scale = 0)
	public Float getMontoTotal() {
		return this.montoTotal;
	}

	public void setMontoTotal(Float montoTotal) {
		this.montoTotal = montoTotal;
	}

}
