package ar.TpDisenio2019.Mapping;
// Generated 3/12/2019 08:29:13 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "pais", catalog = "dbelaseguradov4")
public class Pais  {

	private int idPais;
	private String nombre;

	public Pais() {
	}

	public Pais(int idPais) {
		this.idPais = idPais;
	}

	public Pais(int idPais, String nombre) {
		this.idPais = idPais;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "idPais", unique = true, nullable = false)
	public int getIdPais() {
		return this.idPais;
	}

	public void setIdPais(int idPais) {
		this.idPais = idPais;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
