package ar.TpDisenio2019.Modelo;
// Generated 22/01/2020 22:35:34 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Aniomodelo generated by hbm2java
 */
@Entity
@Table(name = "aniomodelo", catalog = "dbelaseguradov4")
public class Aniomodelo implements java.io.Serializable {

	private AniomodeloId id;
	private Aniodevehiculo aniodevehiculo;
	private Modelo modelo;

	public Aniomodelo() {
	}

	public Aniomodelo(AniomodeloId id, Aniodevehiculo aniodevehiculo, Modelo modelo) {
		this.id = id;
		this.aniodevehiculo = aniodevehiculo;
		this.modelo = modelo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idAnioModelo", column = @Column(name = "idAnioModelo", nullable = false)),
			@AttributeOverride(name = "idModelo", column = @Column(name = "idModelo", nullable = false)),
			@AttributeOverride(name = "idAnioDeVehiculo", column = @Column(name = "idAnioDeVehiculo", nullable = false)) })
	public AniomodeloId getId() {
		return this.id;
	}

	public void setId(AniomodeloId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAnioDeVehiculo", nullable = false, insertable = false, updatable = false)
	public Aniodevehiculo getAniodevehiculo() {
		return this.aniodevehiculo;
	}

	public void setAniodevehiculo(Aniodevehiculo aniodevehiculo) {
		this.aniodevehiculo = aniodevehiculo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idModelo", nullable = false, insertable = false, updatable = false)
	public Modelo getModelo() {
		return this.modelo;
	}

	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}

}
