package ar.TpDisenio2019.Modelo;
// Generated 10/12/2019 00:35:33 by Hibernate Tools 4.3.5.Final

import java.util.Date;


import javax.persistence.Column;
import javax.persistence.Entity;

import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aniodevehiculo generated by hbm2java
 */
@Entity
@Table(name = "aniodevehiculo", catalog = "dbelaseguradov4")
public class Aniodevehiculo  {

	private Integer idAnioDeVehiculo;
	private Date anio;
	

	public Aniodevehiculo() {
	}
	public Aniodevehiculo(Integer idAnioDeVehiculo,Date anio) {
		this.idAnioDeVehiculo=idAnioDeVehiculo;
		this.anio=anio;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAnioDeVehiculo", unique = true, nullable = false)
	public Integer getIdAnioDeVehiculo() {
		return this.idAnioDeVehiculo;
	}

	public void setIdAnioDeVehiculo(Integer idAnioDeVehiculo) {
		this.idAnioDeVehiculo = idAnioDeVehiculo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anio", length = 0)
	public Date getAnio() {
		return this.anio;
	}

	public void setAnio(Date anio) {
		this.anio = anio;
	}

	

}
