package ar.TpDisenio2019.Modelo;
// Generated 3/12/2019 07:40:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "dbelaseguradov4")
public class Cliente  {

	private int idCliente;
	private Estadocivil idEstadoCivil;
	private Profesion idProfesion;
	private Direccion idDireccion;
	private Condicioniva idCondicionIva;
	private Tipodedocumento idTipoDeDocumento;
	private Estadocliente idEstadoCliente;
	private String nombre;
	private String apellido;
	private Integer nroDocumento;
	private String correoElectronico;
	private Date anioDeRegistro;
	private Integer nroCuil;
	private Integer nroCliente;

	public Cliente() {
	}

	public Cliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public Cliente(int idCliente, Estadocivil idEstadoCivil, Profesion idProfesion, Direccion idDireccion,
			Condicioniva idCondicionIva, Tipodedocumento idTipoDeDocumento, Estadocliente idEstadoCliente, String nombre, String apellido,
			Integer nroDocumento, String correoElectronico, Date anioDeRegistro, Integer nroCuil, Integer nroCliente) {
		this.idCliente = idCliente;
		this.idEstadoCivil = idEstadoCivil;
		this.idProfesion = idProfesion;
		this.idDireccion = idDireccion;
		this.idCondicionIva = idCondicionIva;
		this.idTipoDeDocumento = idTipoDeDocumento;
		this.idEstadoCliente = idEstadoCliente;
		this.nombre = nombre;
		this.apellido = apellido;
		this.nroDocumento = nroDocumento;
		this.correoElectronico = correoElectronico;
		this.anioDeRegistro = anioDeRegistro;
		this.nroCuil = nroCuil;
		this.nroCliente = nroCliente;
	}

	@Id

	@Column(name = "idCliente", unique = true, nullable = false)
	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "idEstadoCivil")
	public Estadocivil getIdEstadoCivil() {
		return this.idEstadoCivil;
	}

	public void setIdEstadoCivil(Estadocivil idEstadoCivil) {
		this.idEstadoCivil = idEstadoCivil;
	}

	@Column(name = "idProfesion")
	public Profesion getIdProfesion() {
		return this.idProfesion;
	}

	public void setIdProfesion(Profesion idProfesion) {
		this.idProfesion = idProfesion;
	}

	@Column(name = "idDireccion")
	public Direccion getIdDireccion() {
		return this.idDireccion;
	}

	public void setIdDireccion(Direccion idDireccion) {
		this.idDireccion = idDireccion;
	}

	@Column(name = "idCondicionIva")
	public Condicioniva getIdCondicionIva() {
		return this.idCondicionIva;
	}

	public void setIdCondicionIva(Condicioniva idCondicionIva) {
		this.idCondicionIva = idCondicionIva;
	}

	@Column(name = "idTipoDeDocumento")
	public Tipodedocumento getIdTipoDeDocumento() {
		return this.idTipoDeDocumento;
	}

	public void setIdTipoDeDocumento(Tipodedocumento idTipoDeDocumento) {
		this.idTipoDeDocumento = idTipoDeDocumento;
	}

	@Column(name = "idEstadoCliente")
	public Estadocliente getIdEstadoCliente() {
		return this.idEstadoCliente;
	}

	public void setIdEstadoCliente(Estadocliente idEstadoCliente) {
		this.idEstadoCliente = idEstadoCliente;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", length = 50)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "nroDocumento")
	public Integer getNroDocumento() {
		return this.nroDocumento;
	}

	public void setNroDocumento(Integer nroDocumento) {
		this.nroDocumento = nroDocumento;
	}

	@Column(name = "correoElectronico", length = 50)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anioDeRegistro", length = 0)
	public Date getAnioDeRegistro() {
		return this.anioDeRegistro;
	}

	public void setAnioDeRegistro(Date anioDeRegistro) {
		this.anioDeRegistro = anioDeRegistro;
	}

	@Column(name = "nroCuil")
	public Integer getNroCuil() {
		return this.nroCuil;
	}

	public void setNroCuil(Integer nroCuil) {
		this.nroCuil = nroCuil;
	}

	@Column(name = "nroCliente")
	public Integer getNroCliente() {
		return this.nroCliente;
	}

	public void setNroCliente(Integer nroCliente) {
		this.nroCliente = nroCliente;
	}

}
