package ar.TpDisenio2019.Modelo;
// Generated 3/12/2019 07:40:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Formasdepago generated by hbm2java
 */
@Entity
@Table(name = "formasdepago", catalog = "dbelaseguradov4")
public class Formasdepago  {

	private int idFormasDePago;
	private String nombre;

	public Formasdepago() {
	}

	public Formasdepago(int idFormasDePago) {
		this.idFormasDePago = idFormasDePago;
	}

	public Formasdepago(int idFormasDePago, String nombre) {
		this.idFormasDePago = idFormasDePago;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "idFormasDePago", unique = true, nullable = false)
	public int getIdFormasDePago() {
		return this.idFormasDePago;
	}

	public void setIdFormasDePago(int idFormasDePago) {
		this.idFormasDePago = idFormasDePago;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
