package ar.TpDisenio2019.Modelo;
// Generated 3/12/2019 07:40:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Localidad generated by hbm2java
 */
@Entity
@Table(name = "localidad", catalog = "dbelaseguradov4")
public class Localidad  {

	private int idLocalidad;
	private Provincia idProvincia;
	private String nombre;

	public Localidad() {
	}

	public Localidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	public Localidad(int idLocalidad, Provincia idProvincia, String nombre) {
		this.idLocalidad = idLocalidad;
		this.idProvincia = idProvincia;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "idLocalidad", unique = true, nullable = false)
	public int getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	@Column(name = "idProvincia")
	public Provincia getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(Provincia idProvincia) {
		this.idProvincia = idProvincia;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
