package ar.TpDisenio2019.Modelo;
// Generated 17/11/2019 18:40:49 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DTOLocalidad generated by hbm2java
 */
@Entity
@Table(name = "localidad", catalog = "dbelaseguradov4")
public class Localidad  {

	private int idLocalidad;
	private Provincia provincia;
	private String nombre;

	public Localidad() {
	}

	public Localidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	public Localidad(int idLocalidad, Provincia idProvincia, String nombre) {
		this.idLocalidad = idLocalidad;
		this.provincia = idProvincia;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "idLocalidad", unique = true, nullable = false)
	public int getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(int idLocalidad) {
		this.idLocalidad = idLocalidad;
	}


	public Provincia getProvincia() {
		return provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
