package ar.TpDisenio2019.Modelo;
// Generated 16/12/2019 02:56:06 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name = "marca", catalog = "dbelaseguradov4")
public class Marca implements java.io.Serializable {

	private Integer idMarca;
	private String marca;
	private Set<Modelo> modelos = new HashSet<Modelo>(0);

	public Marca() {
	}

	public Marca(String marca, Set<Modelo> modelos) {
		this.marca = marca;
		this.modelos = modelos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMarca", unique = true, nullable = false)
	public Integer getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(Integer idMarca) {
		this.idMarca = idMarca;
	}

	@Column(name = "marca", length = 50)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set<Modelo> getModelos() {
		return this.modelos;
	}

	public void setModelos(Set<Modelo> modelos) {
		this.modelos = modelos;
	}

}
