package ar.TpDisenio2019.Modelo;
// Generated 10/12/2019 00:35:33 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;

import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

import javax.persistence.Table;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name = "marca", catalog = "dbelaseguradov4")
public class Marca  {

	private Integer idMarca;
	private String marca;
	

	public Marca() {
	}

	public Marca(Integer idMarca,String marca) {
		this.marca = marca;
		this.idMarca = idMarca;
	}public Marca(String marca) {
		this.marca = marca;
	
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMarca", unique = true, nullable = false)
	public Integer getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(Integer idMarca) {
		this.idMarca = idMarca;
	}

	@Column(name = "marca", length = 50)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}



}
