package ar.TpDisenio2019.Modelo;
// Generated 10/12/2019 00:35:33 by Hibernate Tools 4.3.5.Final



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.Table;

/**
 * Medidasdeseguridad generated by hbm2java
 */
@Entity
@Table(name = "medidasdeseguridad", catalog = "dbelaseguradov4")
public class Medidasdeseguridad  {

	private Integer idMedidasSeguridad;
	private Medidasdeseguridadporc medidasdeseguridadporc;
	private String nombre;
	private Float porcentaje;


	public Medidasdeseguridad() {
	}

	public Medidasdeseguridad(Medidasdeseguridadporc medidasdeseguridadporc) {
		this.medidasdeseguridadporc = medidasdeseguridadporc;
	}

	public Medidasdeseguridad(Medidasdeseguridadporc medidasdeseguridadporc, String nombre, Float porcentaje) {
		this.medidasdeseguridadporc = medidasdeseguridadporc;
		this.nombre = nombre;
		this.porcentaje = porcentaje;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMedidasSeguridad", unique = true, nullable = false)
	public Integer getIdMedidasSeguridad() {
		return this.idMedidasSeguridad;
	}

	public void setIdMedidasSeguridad(Integer idMedidasSeguridad) {
		this.idMedidasSeguridad = idMedidasSeguridad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMedPorc", nullable = false)
	public Medidasdeseguridadporc getMedidasdeseguridadporc() {
		return this.medidasdeseguridadporc;
	}

	public void setMedidasdeseguridadporc(Medidasdeseguridadporc medidasdeseguridadporc) {
		this.medidasdeseguridadporc = medidasdeseguridadporc;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "porcentaje", precision = 12, scale = 0)
	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}



}
