package ar.TpDisenio2019.Modelo;
// Generated 22/01/2020 22:35:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Medidasdeseguridadporc generated by hbm2java
 */
@Entity
@Table(name = "medidasdeseguridadporc", catalog = "dbelaseguradov4")
public class Medidasdeseguridadporc implements java.io.Serializable {

	private Integer idMedPorc;
	private Float porcentaje;
	private Set<Medidasdeseguridad> medidasdeseguridads = new HashSet<Medidasdeseguridad>(0);
	private Set<Factoresusados> factoresusadoses = new HashSet<Factoresusados>(0);

	public Medidasdeseguridadporc() {
	}

	public Medidasdeseguridadporc(Float porcentaje, Set<Medidasdeseguridad> medidasdeseguridads,
			Set<Factoresusados> factoresusadoses) {
		this.porcentaje = porcentaje;
		this.medidasdeseguridads = medidasdeseguridads;
		this.factoresusadoses = factoresusadoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMedPorc", unique = true, nullable = false)
	public Integer getIdMedPorc() {
		return this.idMedPorc;
	}

	public void setIdMedPorc(Integer idMedPorc) {
		this.idMedPorc = idMedPorc;
	}

	@Column(name = "porcentaje", precision = 12, scale = 0)
	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medidasdeseguridadporc")
	public Set<Medidasdeseguridad> getMedidasdeseguridads() {
		return this.medidasdeseguridads;
	}

	public void setMedidasdeseguridads(Set<Medidasdeseguridad> medidasdeseguridads) {
		this.medidasdeseguridads = medidasdeseguridads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medidasdeseguridadporc")
	public Set<Factoresusados> getFactoresusadoses() {
		return this.factoresusadoses;
	}

	public void setFactoresusadoses(Set<Factoresusados> factoresusadoses) {
		this.factoresusadoses = factoresusadoses;
	}

}
