package ar.TpDisenio2019.Modelo;
// Generated 17/11/2019 18:40:49 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DTOMedidasdeseguridadporc generated by hbm2java
 */
@Entity
@Table(name = "medidasdeseguridadporc", catalog = "dbelaseguradov4")
public class Medidasdeseguridadporc {

	private int idMedPorc;
	private float porcentaje;
	
	

	public Medidasdeseguridadporc(int idMedPorc, float porcentaje) {
		super();
		this.idMedPorc = idMedPorc;
		this.porcentaje = porcentaje;
	}

	public float getPorcentaje() {
		return porcentaje;
	}

	public void setPorcentaje(float porcentaje) {
		this.porcentaje = porcentaje;
	}

	public Medidasdeseguridadporc(int idMedPorc) {
		this.idMedPorc = idMedPorc;
	}
	
	

	@Id

	@Column(name = "idMedPorc", unique = true, nullable = false)
	public int getIdMedPorc() {
		return this.idMedPorc;
	}

	public void setIdMedPorc(int idMedPorc) {
		this.idMedPorc = idMedPorc;
	}

}
