package ar.TpDisenio2019.Modelo;
// Generated 3/12/2019 07:40:53 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Medidasdeseguridadporc generated by hbm2java
 */
@Entity
@Table(name = "medidasdeseguridadporc", catalog = "dbelaseguradov4")
public class Medidasdeseguridadporc  {

	private int idMedPorc;
	private Float porcentaje;

	public Medidasdeseguridadporc() {
	}

	public Medidasdeseguridadporc(int idMedPorc) {
		this.idMedPorc = idMedPorc;
	}

	public Medidasdeseguridadporc(int idMedPorc, Float porcentaje) {
		this.idMedPorc = idMedPorc;
		this.porcentaje = porcentaje;
	}

	@Id

	@Column(name = "idMedPorc", unique = true, nullable = false)
	public int getIdMedPorc() {
		return this.idMedPorc;
	}

	public void setIdMedPorc(int idMedPorc) {
		this.idMedPorc = idMedPorc;
	}

	@Column(name = "porcentaje", precision = 12, scale = 0)
	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

}
