package ar.TpDisenio2019.Modelo;
// Generated 10/12/2019 00:35:33 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "dbelaseguradov4")
public class Modelo  {

	private Integer idModelo;
	private Aniodevehiculo aniodevehiculo;
	private Marca marca;
	private String nombre;
	private Float porcentaje;
	
	public Modelo() {
	}

	public Modelo(Marca marca) {
		this.marca = marca;
	}

	public Modelo(Aniodevehiculo aniodevehiculo, Marca marca, String nombre, Float porcentaje) {
		this.aniodevehiculo = aniodevehiculo;
		this.marca = marca;
		this.nombre = nombre;
		this.porcentaje = porcentaje;
	
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idModelo", unique = true, nullable = false)
	public Integer getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(Integer idModelo) {
		this.idModelo = idModelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAnioDeVehiculo")
	public Aniodevehiculo getAniodevehiculo() {
		return this.aniodevehiculo;
	}

	public void setAniodevehiculo(Aniodevehiculo aniodevehiculo) {
		this.aniodevehiculo = aniodevehiculo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMarca", nullable = false)
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@Column(name = "nombre", length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "porcentaje", precision = 12, scale = 0)
	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

	

}
