package ar.TpDisenio2019.Modelo;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTOModelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "dbelaseguradov4")
public class Modelo implements java.io.Serializable {

	private Integer idModelo;
	private Marca marca;
	private String nombre;
	private Float porcentaje;
	private String modelocol;
	private Set<Aniomodelo> aniomodelos = new HashSet<Aniomodelo>(0);
	private Set<Vehiculo> vehiculos = new HashSet<Vehiculo>(0);

	public Modelo() {
	}

	public Modelo(Marca marca) {
		this.marca = marca;
	}

	public Modelo(Marca marca, String nombre, Float porcentaje, String modelocol, Set<Aniomodelo> aniomodelos,
			Set<Vehiculo> vehiculos) {
		this.marca = marca;
		this.nombre = nombre;
		this.porcentaje = porcentaje;
		this.modelocol = modelocol;
		this.aniomodelos = aniomodelos;
		this.vehiculos = vehiculos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idModelo", unique = true, nullable = false)
	public Integer getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(Integer idModelo) {
		this.idModelo = idModelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMarca", nullable = false)
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@Column(name = "nombre", length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "porcentaje", precision = 12, scale = 0)
	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "modelocol", length = 40)
	public String getModelocol() {
		return this.modelocol;
	}

	public void setModelocol(String modelocol) {
		this.modelocol = modelocol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Aniomodelo> getAniomodelos() {
		return this.aniomodelos;
	}

	public void setAniomodelos(Set<Aniomodelo> aniomodelos) {
		this.aniomodelos = aniomodelos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Vehiculo> getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Set<Vehiculo> vehiculos) {
		this.vehiculos = vehiculos;
	}

}
