package ar.TpDisenio2019.Modelo;
// Generated 10/12/2019 00:35:33 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Modificacionpoliza generated by hbm2java
 */
@Entity
@Table(name = "modificacionpoliza", catalog = "dbelaseguradov4")
public class Modificacionpoliza  {

	private Integer idModificacionPoliza;
	private Datosdehijo datosdehijo;
	private Medidasdeseguridad medidasdeseguridad;
	private Poliza poliza;
	private Tipocobertura tipocobertura;
	private Vehiculo vehiculo;
	private Date anio;
	private String patente;
	private String motor;
	private String chasis;
	private String nroSiniestro;
	private Integer kmPorAnio;
	private Float montoTotal;

	public Modificacionpoliza() {
	}

	public Modificacionpoliza(Datosdehijo datosdehijo, Medidasdeseguridad medidasdeseguridad, Poliza poliza,
			Tipocobertura tipocobertura, Vehiculo vehiculo) {
		this.datosdehijo = datosdehijo;
		this.medidasdeseguridad = medidasdeseguridad;
		this.poliza = poliza;
		this.tipocobertura = tipocobertura;
		this.vehiculo = vehiculo;
	}

	public Modificacionpoliza(Datosdehijo datosdehijo, Medidasdeseguridad medidasdeseguridad, Poliza poliza,
			Tipocobertura tipocobertura, Vehiculo vehiculo, Date anio, String patente, String motor, String chasis,
			String nroSiniestro, Integer kmPorAnio, Float montoTotal) {
		this.datosdehijo = datosdehijo;
		this.medidasdeseguridad = medidasdeseguridad;
		this.poliza = poliza;
		this.tipocobertura = tipocobertura;
		this.vehiculo = vehiculo;
		this.anio = anio;
		this.patente = patente;
		this.motor = motor;
		this.chasis = chasis;
		this.nroSiniestro = nroSiniestro;
		this.kmPorAnio = kmPorAnio;
		this.montoTotal = montoTotal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idModificacionPoliza", unique = true, nullable = false)
	public Integer getIdModificacionPoliza() {
		return this.idModificacionPoliza;
	}

	public void setIdModificacionPoliza(Integer idModificacionPoliza) {
		this.idModificacionPoliza = idModificacionPoliza;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDatosHijo", nullable = false)
	public Datosdehijo getDatosdehijo() {
		return this.datosdehijo;
	}

	public void setDatosdehijo(Datosdehijo datosdehijo) {
		this.datosdehijo = datosdehijo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMedidasSeguridad", nullable = false)
	public Medidasdeseguridad getMedidasdeseguridad() {
		return this.medidasdeseguridad;
	}

	public void setMedidasdeseguridad(Medidasdeseguridad medidasdeseguridad) {
		this.medidasdeseguridad = medidasdeseguridad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "identNroPoliza", nullable = false)
	public Poliza getPoliza() {
		return this.poliza;
	}

	public void setPoliza(Poliza poliza) {
		this.poliza = poliza;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoCobertura", nullable = false)
	public Tipocobertura getTipocobertura() {
		return this.tipocobertura;
	}

	public void setTipocobertura(Tipocobertura tipocobertura) {
		this.tipocobertura = tipocobertura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idVehiculo", nullable = false)
	public Vehiculo getVehiculo() {
		return this.vehiculo;
	}

	public void setVehiculo(Vehiculo vehiculo) {
		this.vehiculo = vehiculo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anio", length = 0)
	public Date getAnio() {
		return this.anio;
	}

	public void setAnio(Date anio) {
		this.anio = anio;
	}

	@Column(name = "patente", length = 10)
	public String getPatente() {
		return this.patente;
	}

	public void setPatente(String patente) {
		this.patente = patente;
	}

	@Column(name = "motor", length = 20)
	public String getMotor() {
		return this.motor;
	}

	public void setMotor(String motor) {
		this.motor = motor;
	}

	@Column(name = "chasis", length = 20)
	public String getChasis() {
		return this.chasis;
	}

	public void setChasis(String chasis) {
		this.chasis = chasis;
	}

	@Column(name = "nroSiniestro", length = 10)
	public String getNroSiniestro() {
		return this.nroSiniestro;
	}

	public void setNroSiniestro(String nroSiniestro) {
		this.nroSiniestro = nroSiniestro;
	}

	@Column(name = "kmPorAnio")
	public Integer getKmPorAnio() {
		return this.kmPorAnio;
	}

	public void setKmPorAnio(Integer kmPorAnio) {
		this.kmPorAnio = kmPorAnio;
	}

	@Column(name = "montoTotal", precision = 12, scale = 0)
	public Float getMontoTotal() {
		return this.montoTotal;
	}

	public void setMontoTotal(Float montoTotal) {
		this.montoTotal = montoTotal;
	}

}
