package ar.TpDisenio2019.Modelo;
// Generated 10/12/2019 00:35:33 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;

import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

import javax.persistence.Table;

/**
 * Numeropoliza generated by hbm2java
 */
@Entity
@Table(name = "numeropoliza", catalog = "dbelaseguradov4")
public class Numeropoliza {

	private Integer nroPoliza;
	private int nroSucursal;
	private int aleatorio;
	private int secuencia;


	public Numeropoliza() {
	}

	public Numeropoliza(int nroSucursal, int aleatorio, int secuencia) {
		this.nroSucursal = nroSucursal;
		this.aleatorio = aleatorio;
		this.secuencia = secuencia;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "nroPoliza", unique = true, nullable = false)
	public Integer getNroPoliza() {
		return this.nroPoliza;
	}

	public void setNroPoliza(Integer nroPoliza) {
		this.nroPoliza = nroPoliza;
	}

	@Column(name = "nroSucursal", nullable = false)
	public int getNroSucursal() {
		return this.nroSucursal;
	}

	public void setNroSucursal(int nroSucursal) {
		this.nroSucursal = nroSucursal;
	}

	@Column(name = "aleatorio", nullable = false)
	public int getAleatorio() {
		return this.aleatorio;
	}

	public void setAleatorio(int aleatorio) {
		this.aleatorio = aleatorio;
	}

	@Column(name = "secuencia", nullable = false)
	public int getSecuencia() {
		return this.secuencia;
	}

	public void setSecuencia(int secuencia) {
		this.secuencia = secuencia;
	}



}
