package ar.TpDisenio2019.Modelo;
// Generated 06/02/2020 17:41:53 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Numeropoliza generated by hbm2java
 */
@Entity
@Table(name = "numeropoliza", catalog = "dbelaseguradov4")
public class Numeropoliza implements java.io.Serializable {

	private long nroPoliza;
	private int nroSucursal;
	private int aleatorio;
	private int secuencia;
	private Set<Poliza> polizas = new HashSet<Poliza>(0);

	public Numeropoliza() {
	}

	public Numeropoliza(long nroPoliza, int nroSucursal, int aleatorio, int secuencia) {
		this.nroPoliza = nroPoliza;
		this.nroSucursal = nroSucursal;
		this.aleatorio = aleatorio;
		this.secuencia = secuencia;
	}

	public Numeropoliza(long nroPoliza, int nroSucursal, int aleatorio, int secuencia, Set<Poliza> polizas) {
		this.nroPoliza = nroPoliza;
		this.nroSucursal = nroSucursal;
		this.aleatorio = aleatorio;
		this.secuencia = secuencia;
		this.polizas = polizas;
	}

	@Id

	@Column(name = "nroPoliza", unique = true, nullable = false)
	public long getNroPoliza() {
		return this.nroPoliza;
	}

	public void setNroPoliza(long nroPoliza) {
		this.nroPoliza = nroPoliza;
	}

	@Column(name = "nroSucursal", nullable = false)
	public int getNroSucursal() {
		return this.nroSucursal;
	}

	public void setNroSucursal(int nroSucursal) {
		this.nroSucursal = nroSucursal;
	}

	@Column(name = "aleatorio", nullable = false)
	public int getAleatorio() {
		return this.aleatorio;
	}

	public void setAleatorio(int aleatorio) {
		this.aleatorio = aleatorio;
	}

	@Column(name = "secuencia", nullable = false)
	public int getSecuencia() {
		return this.secuencia;
	}

	public void setSecuencia(int secuencia) {
		this.secuencia = secuencia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "numeropoliza")
	public Set<Poliza> getPolizas() {
		return this.polizas;
	}

	public void setPolizas(Set<Poliza> polizas) {
		this.polizas = polizas;
	}

}
