package ar.TpDisenio2019.Modelo;
// Generated 16/12/2019 02:56:06 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Operador generated by hbm2java
 */
@Entity
@Table(name = "operador", catalog = "dbelaseguradov4")
public class Operador implements java.io.Serializable {

	private Integer idOperador;
	private String nombre;
	private Set<Recibo> recibos = new HashSet<Recibo>(0);

	public Operador() {
	}

	public Operador(String nombre, Set<Recibo> recibos) {
		this.nombre = nombre;
		this.recibos = recibos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idOperador", unique = true, nullable = false)
	public Integer getIdOperador() {
		return this.idOperador;
	}

	public void setIdOperador(Integer idOperador) {
		this.idOperador = idOperador;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operador")
	public Set<Recibo> getRecibos() {
		return this.recibos;
	}

	public void setRecibos(Set<Recibo> recibos) {
		this.recibos = recibos;
	}

}
