package ar.TpDisenio2019.Modelo;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTOPais generated by hbm2java
 */
@Entity
@Table(name = "pais", catalog = "dbelaseguradov4")
public class Pais implements java.io.Serializable {

	private Integer idPais;
	private String nombre;
	private Set<Provincia> provincias = new HashSet<Provincia>(0);

	public Pais() {
	}

	public Pais(String nombre, Set<Provincia> provincias) {
		this.nombre = nombre;
		this.provincias = provincias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPais", unique = true, nullable = false)
	public Integer getIdPais() {
		return this.idPais;
	}

	public void setIdPais(Integer idPais) {
		this.idPais = idPais;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Provincia> getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Set<Provincia> provincias) {
		this.provincias = provincias;
	}

}
