package ar.TpDisenio2019.Modelo;
// Generated 3/12/2019 07:40:53 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Poliza generated by hbm2java
 */
@Entity
@Table(name = "poliza", catalog = "dbelaseguradov4")
public class Poliza  {

	private int identNroPoliza;
	private Cliente idCliente;
	private Kmporanio idKmPorAnio;
	private Medidasdeseguridad idMedidasSeguridad;
	private Estado idEstado;
	private Integer idEstadoCliente;
	private Numeropoliza nroPoliza;
	private Vehiculo idVehiculo;
	private Parametrosgenerales idParametrosGenerales;
	private Formasdepago idFormasDePago;
	private Tipocobertura idTipoCobertura;
	private Cuota idCuotas;
	private Datosdehijo idDatosHijo;
	private Factoresusados idFacUsados;
	private Siniestro idSiniestro;
	private Date fechaInicioVigencia;
	private Date fechaFinVigencia;
	private Float sumaAsegurada;
	private Character nroSiniestro;
	private Integer cantidad;

	public Poliza() {
	}

	public Poliza(int identNroPoliza) {
		this.identNroPoliza = identNroPoliza;
	}

	public Poliza(int identNroPoliza, Cliente idCliente, Kmporanio idKmPorAnio, Medidasdeseguridad idMedidasSeguridad,
			Estado idEstado, Integer idEstadoCliente, Numeropoliza nroPoliza,Vehiculo idVehiculo,
			Parametrosgenerales idParametrosGenerales,Formasdepago idFormasDePago, Tipocobertura idTipoCobertura, Cuota idCuotas,
			Datosdehijo idDatosHijo, Factoresusados idFacUsados, Siniestro idSiniestro, Date fechaInicioVigencia,
			Date fechaFinVigencia, Float sumaAsegurada, Character nroSiniestro, Integer cantidad) {
		this.identNroPoliza = identNroPoliza;
		this.idCliente = idCliente;
		this.idKmPorAnio = idKmPorAnio;
		this.idMedidasSeguridad = idMedidasSeguridad;
		this.idEstado = idEstado;
		this.idEstadoCliente = idEstadoCliente;
		this.nroPoliza = nroPoliza;
		this.idVehiculo = idVehiculo;
		this.idParametrosGenerales = idParametrosGenerales;
		this.idFormasDePago = idFormasDePago;
		this.idTipoCobertura = idTipoCobertura;
		this.idCuotas = idCuotas;
		this.idDatosHijo = idDatosHijo;
		this.idFacUsados = idFacUsados;
		this.idSiniestro = idSiniestro;
		this.fechaInicioVigencia = fechaInicioVigencia;
		this.fechaFinVigencia = fechaFinVigencia;
		this.sumaAsegurada = sumaAsegurada;
		this.nroSiniestro = nroSiniestro;
		this.cantidad = cantidad;
	}

	@Id

	@Column(name = "identNroPoliza", unique = true, nullable = false)
	public int getIdentNroPoliza() {
		return this.identNroPoliza;
	}

	public void setIdentNroPoliza(int identNroPoliza) {
		this.identNroPoliza = identNroPoliza;
	}

	@Column(name = "idCliente")
	public Cliente getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Cliente idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "idKmPorAnio")
	public Kmporanio getIdKmPorAnio() {
		return this.idKmPorAnio;
	}

	public void setIdKmPorAnio(Kmporanio idKmPorAnio) {
		this.idKmPorAnio = idKmPorAnio;
	}

	@Column(name = "idMedidasSeguridad")
	public Medidasdeseguridad getIdMedidasSeguridad() {
		return this.idMedidasSeguridad;
	}

	public void setIdMedidasSeguridad(Medidasdeseguridad idMedidasSeguridad) {
		this.idMedidasSeguridad = idMedidasSeguridad;
	}

	@Column(name = "idEstado")
	public Estado getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(Estado idEstado) {
		this.idEstado = idEstado;
	}

	@Column(name = "idEstadoCliente")
	public Integer getIdEstadoCliente() {
		return this.idEstadoCliente;
	}

	public void setIdEstadoCliente(Integer idEstadoCliente) {
		this.idEstadoCliente = idEstadoCliente;
	}

	@Column(name = "nroPoliza")
	public Numeropoliza getNroPoliza() {
		return this.nroPoliza;
	}

	public void setNroPoliza(Numeropoliza nroPoliza) {
		this.nroPoliza = nroPoliza;
	}

	@Column(name = "idVehiculo")
	public Vehiculo getIdVehiculo() {
		return this.idVehiculo;
	}

	public void setIdVehiculo(Vehiculo idVehiculo) {
		this.idVehiculo = idVehiculo;
	}

	@Column(name = "idParametrosGenerales")
	public Parametrosgenerales getIdParametrosGenerales() {
		return this.idParametrosGenerales;
	}

	public void setIdParametrosGenerales(Parametrosgenerales idParametrosGenerales) {
		this.idParametrosGenerales = idParametrosGenerales;
	}

	@Column(name = "idFormasDePago")
	public Formasdepago getIdFormasDePago() {
		return this.idFormasDePago;
	}

	public void setIdFormasDePago(Formasdepago idFormasDePago) {
		this.idFormasDePago = idFormasDePago;
	}

	@Column(name = "idTipoCobertura")
	public Tipocobertura getIdTipoCobertura() {
		return this.idTipoCobertura;
	}

	public void setIdTipoCobertura(Tipocobertura idTipoCobertura) {
		this.idTipoCobertura = idTipoCobertura;
	}

	@Column(name = "idCuotas")
	public Cuota getIdCuotas() {
		return this.idCuotas;
	}

	public void setIdCuotas(Cuota idCuotas) {
		this.idCuotas = idCuotas;
	}

	@Column(name = "idDatosHijo")
	public Datosdehijo getIdDatosHijo() {
		return this.idDatosHijo;
	}

	public void setIdDatosHijo(Datosdehijo idDatosHijo) {
		this.idDatosHijo = idDatosHijo;
	}

	@Column(name = "idFacUsados")
	public Factoresusados getIdFacUsados() {
		return this.idFacUsados;
	}

	public void setIdFacUsados(Factoresusados idFacUsados) {
		this.idFacUsados = idFacUsados;
	}

	@Column(name = "idSiniestro")
	public Siniestro getIdSiniestro() {
		return this.idSiniestro;
	}

	public void setIdSiniestro(Siniestro idSiniestro) {
		this.idSiniestro = idSiniestro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaInicioVigencia", length = 10)
	public Date getFechaInicioVigencia() {
		return this.fechaInicioVigencia;
	}

	public void setFechaInicioVigencia(Date fechaInicioVigencia) {
		this.fechaInicioVigencia = fechaInicioVigencia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaFinVigencia", length = 10)
	public Date getFechaFinVigencia() {
		return this.fechaFinVigencia;
	}

	public void setFechaFinVigencia(Date fechaFinVigencia) {
		this.fechaFinVigencia = fechaFinVigencia;
	}

	@Column(name = "sumaAsegurada", precision = 6)
	public Float getSumaAsegurada() {
		return this.sumaAsegurada;
	}

	public void setSumaAsegurada(Float sumaAsegurada) {
		this.sumaAsegurada = sumaAsegurada;
	}

	@Column(name = "nroSiniestro", length = 1)
	public Character getNroSiniestro() {
		return this.nroSiniestro;
	}

	public void setNroSiniestro(Character nroSiniestro) {
		this.nroSiniestro = nroSiniestro;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
