package ar.TpDisenio2019.Modelo;
// Generated 17/11/2019 18:40:49 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DTOPoliza generated by hbm2java
 */
@Entity
@Table(name = "poliza", catalog = "dbelaseguradov4")
public class Poliza  {

	private int identNroPoliza;
	private Cliente cliente;
	private Kmporanio kmporanio;
	private Medidasdeseguridad medidasdeseguridad;
	private Estado  estado;
	private Estadocliente estadoCliente;
	private Numeropoliza nroPoliza;
	private Vehiculo vehiculo;
	private Parametrosgenerales parametrosgenerales;
	private Formasdepago formasdepago;
	private Tipocobertura tipoCobertura;
	private Cuota cuota;
	private Datosdehijo datosdehijo;
	private Factoresusados factoresusados;
	private Siniestro siniestro;
	private Date fechaInicioVigencia;
	private Date fechaFinVigencia;
	private Float sumaAsegurada;
	private Character nroSiniestro;
	private Integer cantidad;

	public Poliza() {
	}

	public Poliza(int identNroPoliza) {
		this.identNroPoliza = identNroPoliza;
	}

	
	
	
	
	public Poliza(int identNroPoliza, Cliente cliente, Kmporanio kmporanio, Medidasdeseguridad medidasdeseguridad,
			Estado estado, Estadocliente estadoCliente, Numeropoliza nroPoliza, Vehiculo vehiculo,
			Parametrosgenerales parametrosgenerales, Formasdepago idFormasDePago, Tipocobertura tipoCobertura,
			Cuota cuota, Datosdehijo datosdehijo, Factoresusados factoresusados, Siniestro siniestro,
			Date fechaInicioVigencia, Date fechaFinVigencia, Float sumaAsegurada, Character nroSiniestro,
			Integer cantidad) {
		super();
		this.identNroPoliza = identNroPoliza;
		this.cliente = cliente;
		this.kmporanio = kmporanio;
		this.medidasdeseguridad = medidasdeseguridad;
		this.estado = estado;
		this.estadoCliente = estadoCliente;
		this.nroPoliza = nroPoliza;
		this.vehiculo = vehiculo;
		this.parametrosgenerales = parametrosgenerales;
		this.formasdepago = idFormasDePago;
		this.tipoCobertura = tipoCobertura;
		this.cuota = cuota;
		this.datosdehijo = datosdehijo;
		this.factoresusados = factoresusados;
		this.siniestro = siniestro;
		this.fechaInicioVigencia = fechaInicioVigencia;
		this.fechaFinVigencia = fechaFinVigencia;
		this.sumaAsegurada = sumaAsegurada;
		this.nroSiniestro = nroSiniestro;
		this.cantidad = cantidad;
	}

	
	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Kmporanio getKmporanio() {
		return kmporanio;
	}

	public void setKmporanio(Kmporanio kmporanio) {
		this.kmporanio = kmporanio;
	}

	public Medidasdeseguridad getMedidasdeseguridad() {
		return medidasdeseguridad;
	}

	public void setMedidasdeseguridad(Medidasdeseguridad medidasdeseguridad) {
		this.medidasdeseguridad = medidasdeseguridad;
	}

	public Estado getEstado() {
		return estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public Estadocliente getEstadoCliente() {
		return estadoCliente;
	}

	public void setEstadoCliente(Estadocliente estadoCliente) {
		this.estadoCliente = estadoCliente;
	}

	public Vehiculo getVehiculo() {
		return vehiculo;
	}

	public void setVehiculo(Vehiculo vehiculo) {
		this.vehiculo = vehiculo;
	}

	public Parametrosgenerales getParametrosgenerales() {
		return parametrosgenerales;
	}

	public void setParametrosgenerales(Parametrosgenerales parametrosgenerales) {
		this.parametrosgenerales = parametrosgenerales;
	}

	public Tipocobertura getTipoCobertura() {
		return tipoCobertura;
	}

	public void setTipoCobertura(Tipocobertura tipoCobertura) {
		this.tipoCobertura = tipoCobertura;
	}

	public Cuota getCuota() {
		return cuota;
	}

	public void setCuota(Cuota cuota) {
		this.cuota = cuota;
	}

	public Datosdehijo getDatosdehijo() {
		return datosdehijo;
	}

	public void setDatosdehijo(Datosdehijo datosdehijo) {
		this.datosdehijo = datosdehijo;
	}

	public Factoresusados getFactoresusados() {
		return factoresusados;
	}

	public void setFactoresusados(Factoresusados factoresusados) {
		this.factoresusados = factoresusados;
	}

	public Siniestro getSiniestro() {
		return siniestro;
	}

	public void setSiniestro(Siniestro siniestro) {
		this.siniestro = siniestro;
	}

	public void setNroPoliza(Numeropoliza nroPoliza) {
		this.nroPoliza = nroPoliza;
	}

	public void setIdFormasDePago(Formasdepago idFormasDePago) {
		this.formasdepago = idFormasDePago;
	}

	public Formasdepago getFormasdepago() {
		return formasdepago;
	}

	public void setFormasdepago(Formasdepago formasdepago) {
		this.formasdepago = formasdepago;
	}

	public Numeropoliza getNroPoliza() {
		return nroPoliza;
	}

	@Id

	@Column(name = "identNroPoliza", unique = true, nullable = false)
	public int getIdentNroPoliza() {
		return this.identNroPoliza;
	}

	public void setIdentNroPoliza(int identNroPoliza) {
		this.identNroPoliza = identNroPoliza;
	}

              
	

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaInicioVigencia", length = 10)
	public Date getFechaInicioVigencia() {
		return this.fechaInicioVigencia;
	}

	public void setFechaInicioVigencia(Date fechaInicioVigencia) {
		this.fechaInicioVigencia = fechaInicioVigencia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaFinVigencia", length = 10)
	public Date getFechaFinVigencia() {
		return this.fechaFinVigencia;
	}

	public void setFechaFinVigencia(Date fechaFinVigencia) {
		this.fechaFinVigencia = fechaFinVigencia;
	}

	@Column(name = "sumaAsegurada", precision = 6)
	public Float getSumaAsegurada() {
		return this.sumaAsegurada;
	}

	public void setSumaAsegurada(Float sumaAsegurada) {
		this.sumaAsegurada = sumaAsegurada;
	}

	@Column(name = "nroSiniestro", length = 1)
	public Character getNroSiniestro() {
		return this.nroSiniestro;
	}

	public void setNroSiniestro(Character nroSiniestro) {
		this.nroSiniestro = nroSiniestro;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
