package ar.TpDisenio2019.Modelo;
// Generated 10/12/2019 00:35:33 by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;

import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

import javax.persistence.Table;

/**
 * Profesion generated by hbm2java
 */
@Entity
@Table(name = "profesion", catalog = "dbelaseguradov4")
public class Profesion {

	private Integer idProfesion;
	private String nombre;


	public Profesion() {
	}

	public Profesion(String nombre) {
		this.nombre = nombre;
	
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idProfesion", unique = true, nullable = false)
	public Integer getIdProfesion() {
		return this.idProfesion;
	}

	public void setIdProfesion(Integer idProfesion) {
		this.idProfesion = idProfesion;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}



}
