package ar.TpDisenio2019.Modelo;
// Generated 17/11/2019 18:40:49 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DTORecibo generated by hbm2java
 */
@Entity
@Table(name = "recibo", catalog = "dbelaseguradov4")
public class Recibo  {

	private int idRecibo;
	private Operador operador;
	private Integer nroRecibo;
	private Date fecha;
	private Integer hora;
	private Date ultimoDiaDePago;
	private Float importeTotal;

	public Recibo() {
	}

	public Recibo(int idRecibo) {
		this.idRecibo = idRecibo;
	}

	public Recibo(int idRecibo, Operador idOperador, Integer nroRecibo, Date fecha, Integer hora, Date ultimoDiaDePago,
			Float importeTotal) {
		this.idRecibo = idRecibo;
		this.operador = idOperador;
		this.nroRecibo = nroRecibo;
		this.fecha = fecha;
		this.hora = hora;
		this.ultimoDiaDePago = ultimoDiaDePago;
		this.importeTotal = importeTotal;
	}

	@Id

	@Column(name = "idRecibo", unique = true, nullable = false)
	public int getIdRecibo() {
		return this.idRecibo;
	}

	public void setIdRecibo(int idRecibo) {
		this.idRecibo = idRecibo;
	}
	
	
	

	@Column(name = "idOperador")
	public Operador getIdOperador() {
		return this.operador;
	}

	public void setIdOperador(Operador idOperador) {
		this.operador = idOperador;
	}

	@Column(name = "nroRecibo")
	public Integer getNroRecibo() {
		return this.nroRecibo;
	}

	public void setNroRecibo(Integer nroRecibo) {
		this.nroRecibo = nroRecibo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "hora")
	public Integer getHora() {
		return this.hora;
	}

	public void setHora(Integer hora) {
		this.hora = hora;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ultimoDiaDePago", length = 10)
	public Date getUltimoDiaDePago() {
		return this.ultimoDiaDePago;
	}

	public void setUltimoDiaDePago(Date ultimoDiaDePago) {
		this.ultimoDiaDePago = ultimoDiaDePago;
	}

	@Column(name = "importeTotal", precision = 12, scale = 0)
	public Float getImporteTotal() {
		return this.importeTotal;
	}

	public void setImporteTotal(Float importeTotal) {
		this.importeTotal = importeTotal;
	}

}
