package ar.TpDisenio2019.Modelo;
// Generated 10/12/2019 00:35:33 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;

import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;

import javax.persistence.Table;

/**
 * Siniestro generated by hbm2java
 */
@Entity
@Table(name = "siniestro", catalog = "dbelaseguradov4")
public class Siniestro  {

	private Integer idSiniestro;
	private Float porcentaje;
	private Integer cantidad;
	

	public Siniestro() {
	}

	public Siniestro(Float porcentaje, Integer cantidad) {
		this.porcentaje = porcentaje;
		this.cantidad = cantidad;
	
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idSiniestro", unique = true, nullable = false)
	public Integer getIdSiniestro() {
		return this.idSiniestro;
	}

	public void setIdSiniestro(Integer idSiniestro) {
		this.idSiniestro = idSiniestro;
	}

	@Column(name = "porcentaje", precision = 12, scale = 0)
	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}



}
