package ar.TpDisenio2019.Modelo;
// Generated 17/11/2019 18:40:49 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DTOTipocobertura generated by hbm2java
 */
@Entity
@Table(name = "tipocobertura", catalog = "dbelaseguradov4")
public class Tipocobertura  {

	private int idTipoCobertura;
	private String tipo;
	private Float porcentaje;
	private String descripcion;

	public Tipocobertura() {
	}

	public Tipocobertura(int idTipoCobertura) {
		this.idTipoCobertura = idTipoCobertura;
	}

	public Tipocobertura(int idTipoCobertura, String tipo, Float porcentaje, String descripcion) {
		this.idTipoCobertura = idTipoCobertura;
		this.tipo = tipo;
		this.porcentaje = porcentaje;
		this.descripcion = descripcion;
	}

	@Id

	@Column(name = "idTipoCobertura", unique = true, nullable = false)
	public int getIdTipoCobertura() {
		return this.idTipoCobertura;
	}

	public void setIdTipoCobertura(int idTipoCobertura) {
		this.idTipoCobertura = idTipoCobertura;
	}

	@Column(name = "tipo", length = 100)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "porcentaje", precision = 12, scale = 0)
	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "descripcion", length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
