package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DTOAniodevehiculo generated by hbm2java
 */
@Entity
@Table(name = "aniodevehiculo", catalog = "dbelaseguradov4")
public class DTOAniodevehiculo implements java.io.Serializable {

	private Integer idAnioDeVehiculo;
	private Date anio;
	private Set<DTOAniomodelo> dTOAniomodelos = new HashSet<DTOAniomodelo>(0);

	public DTOAniodevehiculo() {
	}

	public DTOAniodevehiculo(Date anio, Set<DTOAniomodelo> dTOAniomodelos) {
		this.anio = anio;
		this.dTOAniomodelos = dTOAniomodelos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idAnioDeVehiculo", unique = true, nullable = false)
	public Integer getIdAnioDeVehiculo() {
		return this.idAnioDeVehiculo;
	}

	public void setIdAnioDeVehiculo(Integer idAnioDeVehiculo) {
		this.idAnioDeVehiculo = idAnioDeVehiculo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anio", length = 0)
	public Date getAnio() {
		return this.anio;
	}

	public void setAnio(Date anio) {
		this.anio = anio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aniodevehiculo")
	public Set<DTOAniomodelo> getAniomodelos() {
		return this.dTOAniomodelos;
	}

	public void setAniomodelos(Set<DTOAniomodelo> dTOAniomodelos) {
		this.dTOAniomodelos = dTOAniomodelos;
	}

}
