package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DTOAniomodelo generated by hbm2java
 */
@Entity
@Table(name = "aniomodelo", catalog = "dbelaseguradov4")
public class DTOAniomodelo implements java.io.Serializable {

	private DTOAniomodeloId id;
	private DTOAniodevehiculo dTOAniodevehiculo;
	private DTOModelo dTOModelo;

	public DTOAniomodelo() {
	}

	public DTOAniomodelo(DTOAniomodeloId id, DTOAniodevehiculo dTOAniodevehiculo, DTOModelo dTOModelo) {
		this.id = id;
		this.dTOAniodevehiculo = dTOAniodevehiculo;
		this.dTOModelo = dTOModelo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idAnioModelo", column = @Column(name = "idAnioModelo", nullable = false)),
			@AttributeOverride(name = "idModelo", column = @Column(name = "idModelo", nullable = false)),
			@AttributeOverride(name = "idAnioDeVehiculo", column = @Column(name = "idAnioDeVehiculo", nullable = false)) })
	public DTOAniomodeloId getId() {
		return this.id;
	}

	public void setId(DTOAniomodeloId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAnioDeVehiculo", nullable = false, insertable = false, updatable = false)
	public DTOAniodevehiculo getAniodevehiculo() {
		return this.dTOAniodevehiculo;
	}

	public void setAniodevehiculo(DTOAniodevehiculo dTOAniodevehiculo) {
		this.dTOAniodevehiculo = dTOAniodevehiculo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idModelo", nullable = false, insertable = false, updatable = false)
	public DTOModelo getModelo() {
		return this.dTOModelo;
	}

	public void setModelo(DTOModelo dTOModelo) {
		this.dTOModelo = dTOModelo;
	}

}
