package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DTOCuota generated by hbm2java
 */
@Entity
@Table(name = "cuota", catalog = "dbelaseguradov4")
public class DTOCuota implements java.io.Serializable {

	private Integer idCuotas;
	private DTORecibo dTORecibo;
	private Integer cuotasPagas;
	private Date vencimiento;
	private Float valorOriginal;
	private Float valorPorMora;
	private Float valorTotalaPagar;
	private Float bonificacion;
	private Float recargoPorMora;
	private Set<DTOPoliza> dTOPolizas = new HashSet<DTOPoliza>(0);

	public DTOCuota() {
	}

	public DTOCuota(DTORecibo dTORecibo, Integer cuotasPagas, Date vencimiento, Float valorOriginal, Float valorPorMora,
			Float valorTotalaPagar, Float bonificacion, Float recargoPorMora, Set<DTOPoliza> dTOPolizas) {
		this.dTORecibo = dTORecibo;
		this.cuotasPagas = cuotasPagas;
		this.vencimiento = vencimiento;
		this.valorOriginal = valorOriginal;
		this.valorPorMora = valorPorMora;
		this.valorTotalaPagar = valorTotalaPagar;
		this.bonificacion = bonificacion;
		this.recargoPorMora = recargoPorMora;
		this.dTOPolizas = dTOPolizas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCuotas", unique = true, nullable = false)
	public Integer getIdCuotas() {
		return this.idCuotas;
	}

	public void setIdCuotas(Integer idCuotas) {
		this.idCuotas = idCuotas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRecibo")
	public DTORecibo getRecibo() {
		return this.dTORecibo;
	}

	public void setRecibo(DTORecibo dTORecibo) {
		this.dTORecibo = dTORecibo;
	}

	@Column(name = "cuotasPagas")
	public Integer getCuotasPagas() {
		return this.cuotasPagas;
	}

	public void setCuotasPagas(Integer cuotasPagas) {
		this.cuotasPagas = cuotasPagas;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "vencimiento", length = 10)
	public Date getVencimiento() {
		return this.vencimiento;
	}

	public void setVencimiento(Date vencimiento) {
		this.vencimiento = vencimiento;
	}

	@Column(name = "valorOriginal", precision = 12, scale = 0)
	public Float getValorOriginal() {
		return this.valorOriginal;
	}

	public void setValorOriginal(Float valorOriginal) {
		this.valorOriginal = valorOriginal;
	}

	@Column(name = "valorPorMora", precision = 12, scale = 0)
	public Float getValorPorMora() {
		return this.valorPorMora;
	}

	public void setValorPorMora(Float valorPorMora) {
		this.valorPorMora = valorPorMora;
	}

	@Column(name = "valorTotalaPagar", precision = 12, scale = 0)
	public Float getValorTotalaPagar() {
		return this.valorTotalaPagar;
	}

	public void setValorTotalaPagar(Float valorTotalaPagar) {
		this.valorTotalaPagar = valorTotalaPagar;
	}

	@Column(name = "bonificacion", precision = 12, scale = 0)
	public Float getBonificacion() {
		return this.bonificacion;
	}

	public void setBonificacion(Float bonificacion) {
		this.bonificacion = bonificacion;
	}

	@Column(name = "recargoPorMora", precision = 12, scale = 0)
	public Float getRecargoPorMora() {
		return this.recargoPorMora;
	}

	public void setRecargoPorMora(Float recargoPorMora) {
		this.recargoPorMora = recargoPorMora;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuota")
	public Set<DTOPoliza> getPolizas() {
		return this.dTOPolizas;
	}

	public void setPolizas(Set<DTOPoliza> dTOPolizas) {
		this.dTOPolizas = dTOPolizas;
	}

}
