package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DTOCliente generated by hbm2java
 */
@Entity
@Table(name = "cliente", catalog = "dbelaseguradov4")
public class DTOCliente implements java.io.Serializable {

	private Integer idCliente;
	private DTOCondicioniva dTOCondicioniva;
	private DTODireccion dTODireccion;
	private DTOEstadocivil dTOEstadocivil;
	private DTOEstadocliente dTOEstadocliente;
	private DTOProfesion dTOProfesion;
	private DTOTipodedocumento dTOTipodedocumento;
	private String nombre;
	private String apellido;
	private Integer nroDocumento;
	private String correoElectronico;
	private Date anioDeRegistro;
	private Long nroCuil;
	private Long nroCliente;
	private Set<DTOPoliza> dTOPolizas = new HashSet<DTOPoliza>(0);

	public DTOCliente() {
	}

	public DTOCliente(DTOCondicioniva dTOCondicioniva, DTODireccion dTODireccion, DTOEstadocivil dTOEstadocivil, DTOEstadocliente dTOEstadocliente,
			DTOProfesion dTOProfesion, DTOTipodedocumento dTOTipodedocumento, String nombre, String apellido, Integer nroDocumento,
			String correoElectronico, Date anioDeRegistro, Long nroCuil, Long nroCliente, Set<DTOPoliza> dTOPolizas) {
		this.dTOCondicioniva = dTOCondicioniva;
		this.dTODireccion = dTODireccion;
		this.dTOEstadocivil = dTOEstadocivil;
		this.dTOEstadocliente = dTOEstadocliente;
		this.dTOProfesion = dTOProfesion;
		this.dTOTipodedocumento = dTOTipodedocumento;
		this.nombre = nombre;
		this.apellido = apellido;
		this.nroDocumento = nroDocumento;
		this.correoElectronico = correoElectronico;
		this.anioDeRegistro = anioDeRegistro;
		this.nroCuil = nroCuil;
		this.nroCliente = nroCliente;
		this.dTOPolizas = dTOPolizas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCliente", unique = true, nullable = false)
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCondicionIVA")
	public DTOCondicioniva getCondicioniva() {
		return this.dTOCondicioniva;
	}

	public void setCondicioniva(DTOCondicioniva dTOCondicioniva) {
		this.dTOCondicioniva = dTOCondicioniva;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDireccion")
	public DTODireccion getDireccion() {
		return this.dTODireccion;
	}

	public void setDireccion(DTODireccion dTODireccion) {
		this.dTODireccion = dTODireccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEstadoCivil")
	public DTOEstadocivil getEstadocivil() {
		return this.dTOEstadocivil;
	}

	public void setEstadocivil(DTOEstadocivil dTOEstadocivil) {
		this.dTOEstadocivil = dTOEstadocivil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEstadoCliente")
	public DTOEstadocliente getEstadocliente() {
		return this.dTOEstadocliente;
	}

	public void setEstadocliente(DTOEstadocliente dTOEstadocliente) {
		this.dTOEstadocliente = dTOEstadocliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProfesion")
	public DTOProfesion getProfesion() {
		return this.dTOProfesion;
	}

	public void setProfesion(DTOProfesion dTOProfesion) {
		this.dTOProfesion = dTOProfesion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoDeDocumento")
	public DTOTipodedocumento getTipodedocumento() {
		return this.dTOTipodedocumento;
	}

	public void setTipodedocumento(DTOTipodedocumento dTOTipodedocumento) {
		this.dTOTipodedocumento = dTOTipodedocumento;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", length = 50)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "nroDocumento")
	public Integer getNroDocumento() {
		return this.nroDocumento;
	}

	public void setNroDocumento(Integer nroDocumento) {
		this.nroDocumento = nroDocumento;
	}

	@Column(name = "correoElectronico", length = 50)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anioDeRegistro", length = 0)
	public Date getAnioDeRegistro() {
		return this.anioDeRegistro;
	}

	public void setAnioDeRegistro(Date anioDeRegistro) {
		this.anioDeRegistro = anioDeRegistro;
	}

	@Column(name = "nroCuil")
	public Long getNroCuil() {
		return this.nroCuil;
	}

	public void setNroCuil(Long nroCuil) {
		this.nroCuil = nroCuil;
	}

	@Column(name = "nroCliente")
	public Long getNroCliente() {
		return this.nroCliente;
	}

	public void setNroCliente(Long nroCliente) {
		this.nroCliente = nroCliente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<DTOPoliza> getPolizas() {
		return this.dTOPolizas;
	}

	public void setPolizas(Set<DTOPoliza> dTOPolizas) {
		this.dTOPolizas = dTOPolizas;
	}

}
