package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTODireccion generated by hbm2java
 */
@Entity
@Table(name = "direccion", catalog = "dbelaseguradov4")
public class DTODireccion implements java.io.Serializable {

	private Integer idDireccion;
	private DTOLocalidad dTOLocalidad;
	private String calle;
	private Integer numero;
	private Integer piso;
	private String departamento;
	private Set<DTOCliente> dTOClientes = new HashSet<DTOCliente>(0);

	public DTODireccion() {
	}

	public DTODireccion(DTOLocalidad dTOLocalidad, String calle, Integer numero, Integer piso, String departamento,
			Set<DTOCliente> dTOClientes) {
		this.dTOLocalidad = dTOLocalidad;
		this.calle = calle;
		this.numero = numero;
		this.piso = piso;
		this.departamento = departamento;
		this.dTOClientes = dTOClientes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDireccion", unique = true, nullable = false)
	public Integer getIdDireccion() {
		return this.idDireccion;
	}

	public void setIdDireccion(Integer idDireccion) {
		this.idDireccion = idDireccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLocalidad")
	public DTOLocalidad getLocalidad() {
		return this.dTOLocalidad;
	}

	public void setLocalidad(DTOLocalidad dTOLocalidad) {
		this.dTOLocalidad = dTOLocalidad;
	}

	@Column(name = "calle", length = 50)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@Column(name = "piso")
	public Integer getPiso() {
		return this.piso;
	}

	public void setPiso(Integer piso) {
		this.piso = piso;
	}

	@Column(name = "departamento", length = 50)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "direccion")
	public Set<DTOCliente> getClientes() {
		return this.dTOClientes;
	}

	public void setClientes(Set<DTOCliente> dTOClientes) {
		this.dTOClientes = dTOClientes;
	}

}
