package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DTODatosdehijo generated by hbm2java
 */
@Entity
@Table(name = "datosdehijo", catalog = "dbelaseguradov4")
public class DTODatosdehijo implements java.io.Serializable {

	private Integer idDatosHijo;
	private DTOEstadocivil dTOEstadocivil;
	private Date fecha;
	private String sexo;
	private Float porcentaje;
	private Set<DTOModificacionpoliza> dTOModificacionpolizas = new HashSet<DTOModificacionpoliza>(0);
	private Set<DTOPoliza> dTOPolizas = new HashSet<DTOPoliza>(0);

	public DTODatosdehijo() {
	}

	public DTODatosdehijo(DTOEstadocivil dTOEstadocivil, Date fecha, String sexo, Float porcentaje,
			Set<DTOModificacionpoliza> dTOModificacionpolizas, Set<DTOPoliza> dTOPolizas) {
		this.dTOEstadocivil = dTOEstadocivil;
		this.fecha = fecha;
		this.sexo = sexo;
		this.porcentaje = porcentaje;
		this.dTOModificacionpolizas = dTOModificacionpolizas;
		this.dTOPolizas = dTOPolizas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idDatosHijo", unique = true, nullable = false)
	public Integer getIdDatosHijo() {
		return this.idDatosHijo;
	}

	public void setIdDatosHijo(Integer idDatosHijo) {
		this.idDatosHijo = idDatosHijo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEstadoCivil")
	public DTOEstadocivil getEstadocivil() {
		return this.dTOEstadocivil;
	}

	public void setEstadocivil(DTOEstadocivil dTOEstadocivil) {
		this.dTOEstadocivil = dTOEstadocivil;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "sexo", length = 9)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "porcentaje", precision = 12, scale = 0)
	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datosdehijo")
	public Set<DTOModificacionpoliza> getModificacionpolizas() {
		return this.dTOModificacionpolizas;
	}

	public void setModificacionpolizas(Set<DTOModificacionpoliza> dTOModificacionpolizas) {
		this.dTOModificacionpolizas = dTOModificacionpolizas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datosdehijo")
	public Set<DTOPoliza> getPolizas() {
		return this.dTOPolizas;
	}

	public void setPolizas(Set<DTOPoliza> dTOPolizas) {
		this.dTOPolizas = dTOPolizas;
	}

}
