package ar.TpDisenio2019.DTO;
// Generated 17/11/2019 18:40:49 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DTODatosdehijo generated by hbm2java
 */
@Entity
@Table(name = "datosdehijo", catalog = "dbelaseguradov4")
public class DTODatosdehijo {

	private int idDatosHijo;
	private DTOEstadocivil estadocivil;
	private Date fecha;
	private String sexo;
	private Float porcentaje;

	public DTODatosdehijo() {
	}

	public DTODatosdehijo(int idDatosHijo) {
		this.idDatosHijo = idDatosHijo;
	}

	public DTODatosdehijo(int idDatosHijo, DTOEstadocivil idEstadoCivil, Date fecha, String sexo, Float porcentaje) {
		this.idDatosHijo = idDatosHijo;
		this.estadocivil = idEstadoCivil;
		this.fecha = fecha;
		this.sexo = sexo;
		this.porcentaje = porcentaje;
	}

	@Id

	@Column(name = "idDatosHijo", unique = true, nullable = false)
	public int getIdDatosHijo() {
		return this.idDatosHijo;
	}

	public void setIdDatosHijo(int idDatosHijo) {
		this.idDatosHijo = idDatosHijo;
	}



	public DTOEstadocivil getEstadocivil() {
		return estadocivil;
	}

	public void setEstadocivil(DTOEstadocivil estadocivil) {
		this.estadocivil = estadocivil;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "sexo", length = 9)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "porcentaje", precision = 12, scale = 0)
	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

}
