package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTOEstadocivil generated by hbm2java
 */
@Entity
@Table(name = "estadocivil", catalog = "dbelaseguradov4")
public class DTOEstadocivil implements java.io.Serializable {

	private Integer idEstadoCivil;
	private String nombre;
	private Set<DTODatosdehijo> dTODatosdehijos = new HashSet<DTODatosdehijo>(0);
	private Set<DTOCliente> dTOClientes = new HashSet<DTOCliente>(0);

	public DTOEstadocivil() {
	}

	public DTOEstadocivil(String nombre, Set<DTODatosdehijo> dTODatosdehijos, Set<DTOCliente> dTOClientes) {
		this.nombre = nombre;
		this.dTODatosdehijos = dTODatosdehijos;
		this.dTOClientes = dTOClientes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEstadoCivil", unique = true, nullable = false)
	public Integer getIdEstadoCivil() {
		return this.idEstadoCivil;
	}

	public void setIdEstadoCivil(Integer idEstadoCivil) {
		this.idEstadoCivil = idEstadoCivil;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadocivil")
	public Set<DTODatosdehijo> getDatosdehijos() {
		return this.dTODatosdehijos;
	}

	public void setDatosdehijos(Set<DTODatosdehijo> dTODatosdehijos) {
		this.dTODatosdehijos = dTODatosdehijos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadocivil")
	public Set<DTOCliente> getClientes() {
		return this.dTOClientes;
	}

	public void setClientes(Set<DTOCliente> dTOClientes) {
		this.dTOClientes = dTOClientes;
	}

}
