package ar.TpDisenio2019.DTO;
// Generated 17/11/2019 18:40:49 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DTOEstado generated by hbm2java
 */
@Entity
@Table(name = "estado", catalog = "dbelaseguradov4")
public class DTOEstado {

	private int idEstado;
	private String tipo;

	public DTOEstado() {
	}

	public DTOEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	public DTOEstado(int idEstado, String tipo) {
		this.idEstado = idEstado;
		this.tipo = tipo;
	}

	@Id

	@Column(name = "idEstado", unique = true, nullable = false)
	public int getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(int idEstado) {
		this.idEstado = idEstado;
	}

	@Column(name = "tipo", length = 30)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
