package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTOFormasdepago generated by hbm2java
 */
@Entity
@Table(name = "formasdepago", catalog = "dbelaseguradov4")
public class DTOFormasdepago implements java.io.Serializable {

	private Integer idFormasDePago;
	private String nombre;
	private Set<DTOPoliza> dTOPolizas = new HashSet<DTOPoliza>(0);

	public DTOFormasdepago() {
	}

	public DTOFormasdepago(String nombre, Set<DTOPoliza> dTOPolizas) {
		this.nombre = nombre;
		this.dTOPolizas = dTOPolizas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idFormasDePago", unique = true, nullable = false)
	public Integer getIdFormasDePago() {
		return this.idFormasDePago;
	}

	public void setIdFormasDePago(Integer idFormasDePago) {
		this.idFormasDePago = idFormasDePago;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formasdepago")
	public Set<DTOPoliza> getPolizas() {
		return this.dTOPolizas;
	}

	public void setPolizas(Set<DTOPoliza> dTOPolizas) {
		this.dTOPolizas = dTOPolizas;
	}

}
