package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTOKmporanio generated by hbm2java
 */
@Entity
@Table(name = "kmporanio", catalog = "dbelaseguradov4")
public class DTOKmporanio implements java.io.Serializable {

	private Integer idKmPorAnio;
	private Float porcentaje;
	private Set<DTOPoliza> dTOPolizas = new HashSet<DTOPoliza>(0);

	public DTOKmporanio() {
	}

	public DTOKmporanio(Float porcentaje, Set<DTOPoliza> dTOPolizas) {
		this.porcentaje = porcentaje;
		this.dTOPolizas = dTOPolizas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idKmPorAnio", unique = true, nullable = false)
	public Integer getIdKmPorAnio() {
		return this.idKmPorAnio;
	}

	public void setIdKmPorAnio(Integer idKmPorAnio) {
		this.idKmPorAnio = idKmPorAnio;
	}

	@Column(name = "porcentaje", precision = 12, scale = 0)
	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kmporanio")
	public Set<DTOPoliza> getPolizas() {
		return this.dTOPolizas;
	}

	public void setPolizas(Set<DTOPoliza> dTOPolizas) {
		this.dTOPolizas = dTOPolizas;
	}

}
