package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTOLocalidad generated by hbm2java
 */
@Entity
@Table(name = "localidad", catalog = "dbelaseguradov4")
public class DTOLocalidad implements java.io.Serializable {

	private Integer idLocalidad;
	private DTOProvincia dTOProvincia;
	private String nombre;
	private Set<DTODireccion> dTODireccions = new HashSet<DTODireccion>(0);

	public DTOLocalidad() {
	}

	public DTOLocalidad(DTOProvincia dTOProvincia, String nombre, Set<DTODireccion> dTODireccions) {
		this.dTOProvincia = dTOProvincia;
		this.nombre = nombre;
		this.dTODireccions = dTODireccions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idLocalidad", unique = true, nullable = false)
	public Integer getIdLocalidad() {
		return this.idLocalidad;
	}

	public void setIdLocalidad(Integer idLocalidad) {
		this.idLocalidad = idLocalidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProvincia")
	public DTOProvincia getProvincia() {
		return this.dTOProvincia;
	}

	public void setProvincia(DTOProvincia dTOProvincia) {
		this.dTOProvincia = dTOProvincia;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localidad")
	public Set<DTODireccion> getDireccions() {
		return this.dTODireccions;
	}

	public void setDireccions(Set<DTODireccion> dTODireccions) {
		this.dTODireccions = dTODireccions;
	}

}
