package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTOMedidasdeseguridadporc generated by hbm2java
 */
@Entity
@Table(name = "medidasdeseguridadporc", catalog = "dbelaseguradov4")
public class DTOMedidasdeseguridadporc implements java.io.Serializable {

	private Integer idMedPorc;
	private Float porcentaje;
	private Set<DTOMedidasdeseguridad> dTOMedidasdeseguridads = new HashSet<DTOMedidasdeseguridad>(0);
	private Set<DTOFactoresusados> factoresusadoses = new HashSet<DTOFactoresusados>(0);

	public DTOMedidasdeseguridadporc() {
	}

	public DTOMedidasdeseguridadporc(Float porcentaje, Set<DTOMedidasdeseguridad> dTOMedidasdeseguridads,
			Set<DTOFactoresusados> factoresusadoses) {
		this.porcentaje = porcentaje;
		this.dTOMedidasdeseguridads = dTOMedidasdeseguridads;
		this.factoresusadoses = factoresusadoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMedPorc", unique = true, nullable = false)
	public Integer getIdMedPorc() {
		return this.idMedPorc;
	}

	public void setIdMedPorc(Integer idMedPorc) {
		this.idMedPorc = idMedPorc;
	}

	@Column(name = "porcentaje", precision = 12, scale = 0)
	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medidasdeseguridadporc")
	public Set<DTOMedidasdeseguridad> getMedidasdeseguridads() {
		return this.dTOMedidasdeseguridads;
	}

	public void setMedidasdeseguridads(Set<DTOMedidasdeseguridad> dTOMedidasdeseguridads) {
		this.dTOMedidasdeseguridads = dTOMedidasdeseguridads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medidasdeseguridadporc")
	public Set<DTOFactoresusados> getFactoresusadoses() {
		return this.factoresusadoses;
	}

	public void setFactoresusadoses(Set<DTOFactoresusados> factoresusadoses) {
		this.factoresusadoses = factoresusadoses;
	}

}
