package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTOMedidasdeseguridad generated by hbm2java
 */
@Entity
@Table(name = "medidasdeseguridad", catalog = "dbelaseguradov4")
public class DTOMedidasdeseguridad implements java.io.Serializable {

	private Integer idMedidasSeguridad;
	private DTOMedidasdeseguridadporc dTOMedidasdeseguridadporc;
	private String nombre;
	private Float porcentaje;
	private Set<DTOPoliza> dTOPolizas = new HashSet<DTOPoliza>(0);
	private Set<DTOModificacionpoliza> dTOModificacionpolizas = new HashSet<DTOModificacionpoliza>(0);

	public DTOMedidasdeseguridad() {
	}

	public DTOMedidasdeseguridad(DTOMedidasdeseguridadporc dTOMedidasdeseguridadporc) {
		this.dTOMedidasdeseguridadporc = dTOMedidasdeseguridadporc;
	}

	public DTOMedidasdeseguridad(DTOMedidasdeseguridadporc dTOMedidasdeseguridadporc, String nombre, Float porcentaje,
			Set<DTOPoliza> dTOPolizas, Set<DTOModificacionpoliza> dTOModificacionpolizas) {
		this.dTOMedidasdeseguridadporc = dTOMedidasdeseguridadporc;
		this.nombre = nombre;
		this.porcentaje = porcentaje;
		this.dTOPolizas = dTOPolizas;
		this.dTOModificacionpolizas = dTOModificacionpolizas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMedidasSeguridad", unique = true, nullable = false)
	public Integer getIdMedidasSeguridad() {
		return this.idMedidasSeguridad;
	}

	public void setIdMedidasSeguridad(Integer idMedidasSeguridad) {
		this.idMedidasSeguridad = idMedidasSeguridad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMedPorc", nullable = false)
	public DTOMedidasdeseguridadporc getMedidasdeseguridadporc() {
		return this.dTOMedidasdeseguridadporc;
	}

	public void setMedidasdeseguridadporc(DTOMedidasdeseguridadporc dTOMedidasdeseguridadporc) {
		this.dTOMedidasdeseguridadporc = dTOMedidasdeseguridadporc;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "porcentaje", precision = 12, scale = 0)
	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medidasdeseguridad")
	public Set<DTOPoliza> getPolizas() {
		return this.dTOPolizas;
	}

	public void setPolizas(Set<DTOPoliza> dTOPolizas) {
		this.dTOPolizas = dTOPolizas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medidasdeseguridad")
	public Set<DTOModificacionpoliza> getModificacionpolizas() {
		return this.dTOModificacionpolizas;
	}

	public void setModificacionpolizas(Set<DTOModificacionpoliza> dTOModificacionpolizas) {
		this.dTOModificacionpolizas = dTOModificacionpolizas;
	}

}
