package ar.TpDisenio2019.DTO;
// Generated 17/11/2019 18:40:49 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DTOModificacionpoliza generated by hbm2java
 */
@Entity
@Table(name = "modificacionpoliza", catalog = "dbelaseguradov4")
public class DTOModificacionpoliza  {

	private int idModificacionPoliza;
	private DTOVehiculo vehiculo;
	private DTOMedidasdeseguridad medidasdeseguridad;
	private DTODatosdehijo datosdehijo;
	private DTOTipocobertura tipocobertura;
	private DTOPoliza poliza;
	private Date anio;
	private String patente;
	private String motor;
	private String chasis;
	private String nroSiniestro;
	private Integer kmPorAnio;
	private Float montoTotal;

	public DTOModificacionpoliza() {
	}

	public DTOModificacionpoliza(int idModificacionPoliza, DTOVehiculo idVehiculo, DTOMedidasdeseguridad idMedidasSeguridad, DTODatosdehijo idDatosHijo,
			DTOTipocobertura idTipoCobertura, DTOPoliza identNroPoliza) {
		this.idModificacionPoliza = idModificacionPoliza;
		this.vehiculo = idVehiculo;
		this.medidasdeseguridad = idMedidasSeguridad;
		this.datosdehijo = idDatosHijo;
		this.tipocobertura = idTipoCobertura;
		this.poliza = identNroPoliza;
	}

	public DTOModificacionpoliza(int idModificacionPoliza, DTOVehiculo idVehiculo, DTOMedidasdeseguridad idMedidasSeguridad, DTODatosdehijo idDatosHijo,
			DTOTipocobertura idTipoCobertura, DTOPoliza identNroPoliza, Date anio, String patente, String motor, String chasis,
			String nroSiniestro, Integer kmPorAnio, Float montoTotal) {
		this.idModificacionPoliza = idModificacionPoliza;
		this.vehiculo = idVehiculo;
		this.medidasdeseguridad = idMedidasSeguridad;
		this.datosdehijo = idDatosHijo;
		this.tipocobertura = idTipoCobertura;
		this.poliza = identNroPoliza;
		this.anio = anio;
		this.patente = patente;
		this.motor = motor;
		this.chasis = chasis;
		this.nroSiniestro = nroSiniestro;
		this.kmPorAnio = kmPorAnio;
		this.montoTotal = montoTotal;
	}

	@Id

	@Column(name = "idModificacionPoliza", unique = true, nullable = false)
	public int getIdModificacionPoliza() {
		return this.idModificacionPoliza;
	}

	public void setIdModificacionPoliza(int idModificacionPoliza) {
		this.idModificacionPoliza = idModificacionPoliza;
	}

	
	
	public DTOVehiculo getVehiculo() {
		return vehiculo;
	}

	public void setVehiculo(DTOVehiculo vehiculo) {
		this.vehiculo = vehiculo;
	}

	public DTOMedidasdeseguridad getMedidasdeseguridad() {
		return medidasdeseguridad;
	}

	public void setMedidasdeseguridad(DTOMedidasdeseguridad medidasdeseguridad) {
		this.medidasdeseguridad = medidasdeseguridad;
	}

	public DTODatosdehijo getDatosdehijo() {
		return datosdehijo;
	}

	public void setDatosdehijo(DTODatosdehijo datosdehijo) {
		this.datosdehijo = datosdehijo;
	}

	public DTOTipocobertura getTipocobertura() {
		return tipocobertura;
	}

	public void setTipocobertura(DTOTipocobertura tipocobertura) {
		this.tipocobertura = tipocobertura;
	}

	public DTOPoliza getPoliza() {
		return poliza;
	}

	public void setPoliza(DTOPoliza poliza) {
		this.poliza = poliza;
	}



	@Temporal(TemporalType.DATE)
	@Column(name = "anio", length = 0)
	public Date getAnio() {
		return this.anio;
	}

	public void setAnio(Date anio) {
		this.anio = anio;
	}

	@Column(name = "patente", length = 10)
	public String getPatente() {
		return this.patente;
	}

	public void setPatente(String patente) {
		this.patente = patente;
	}

	@Column(name = "motor", length = 20)
	public String getMotor() {
		return this.motor;
	}

	public void setMotor(String motor) {
		this.motor = motor;
	}

	@Column(name = "chasis", length = 20)
	public String getChasis() {
		return this.chasis;
	}

	public void setChasis(String chasis) {
		this.chasis = chasis;
	}

	@Column(name = "nroSiniestro", length = 10)
	public String getNroSiniestro() {
		return this.nroSiniestro;
	}

	public void setNroSiniestro(String nroSiniestro) {
		this.nroSiniestro = nroSiniestro;
	}

	@Column(name = "kmPorAnio")
	public Integer getKmPorAnio() {
		return this.kmPorAnio;
	}

	public void setKmPorAnio(Integer kmPorAnio) {
		this.kmPorAnio = kmPorAnio;
	}

	@Column(name = "montoTotal", precision = 12, scale = 0)
	public Float getMontoTotal() {
		return this.montoTotal;
	}

	public void setMontoTotal(Float montoTotal) {
		this.montoTotal = montoTotal;
	}

}
