package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTOMarca generated by hbm2java
 */
@Entity
@Table(name = "marca", catalog = "dbelaseguradov4")
public class DTOMarca implements java.io.Serializable {

	private Integer idMarca;
	private String marca;
	private Set<DTOModelo> dTOModelos = new HashSet<DTOModelo>(0);

	public DTOMarca() {
	}

	public DTOMarca(String marca, Set<DTOModelo> dTOModelos) {
		this.marca = marca;
		this.dTOModelos = dTOModelos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMarca", unique = true, nullable = false)
	public Integer getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(Integer idMarca) {
		this.idMarca = idMarca;
	}

	@Column(name = "marca", length = 50)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set<DTOModelo> getModelos() {
		return this.dTOModelos;
	}

	public void setModelos(Set<DTOModelo> dTOModelos) {
		this.dTOModelos = dTOModelos;
	}

}
