package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DTOModificacionpoliza generated by hbm2java
 */
@Entity
@Table(name = "modificacionpoliza", catalog = "dbelaseguradov4")
public class DTOModificacionpoliza implements java.io.Serializable {

	private Integer idModificacionPoliza;
	private DTODatosdehijo dTODatosdehijo;
	private DTOMedidasdeseguridad dTOMedidasdeseguridad;
	private DTOPoliza dTOPoliza;
	private DTOTipocobertura dTOTipocobertura;
	private DTOVehiculo dTOVehiculo;
	private Date anio;
	private String patente;
	private String motor;
	private String chasis;
	private String nroSiniestro;
	private Integer kmPorAnio;
	private Float montoTotal;

	public DTOModificacionpoliza() {
	}

	public DTOModificacionpoliza(DTODatosdehijo dTODatosdehijo, DTOMedidasdeseguridad dTOMedidasdeseguridad, DTOPoliza dTOPoliza,
			DTOTipocobertura dTOTipocobertura, DTOVehiculo dTOVehiculo) {
		this.dTODatosdehijo = dTODatosdehijo;
		this.dTOMedidasdeseguridad = dTOMedidasdeseguridad;
		this.dTOPoliza = dTOPoliza;
		this.dTOTipocobertura = dTOTipocobertura;
		this.dTOVehiculo = dTOVehiculo;
	}

	public DTOModificacionpoliza(DTODatosdehijo dTODatosdehijo, DTOMedidasdeseguridad dTOMedidasdeseguridad, DTOPoliza dTOPoliza,
			DTOTipocobertura dTOTipocobertura, DTOVehiculo dTOVehiculo, Date anio, String patente, String motor, String chasis,
			String nroSiniestro, Integer kmPorAnio, Float montoTotal) {
		this.dTODatosdehijo = dTODatosdehijo;
		this.dTOMedidasdeseguridad = dTOMedidasdeseguridad;
		this.dTOPoliza = dTOPoliza;
		this.dTOTipocobertura = dTOTipocobertura;
		this.dTOVehiculo = dTOVehiculo;
		this.anio = anio;
		this.patente = patente;
		this.motor = motor;
		this.chasis = chasis;
		this.nroSiniestro = nroSiniestro;
		this.kmPorAnio = kmPorAnio;
		this.montoTotal = montoTotal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idModificacionPoliza", unique = true, nullable = false)
	public Integer getIdModificacionPoliza() {
		return this.idModificacionPoliza;
	}

	public void setIdModificacionPoliza(Integer idModificacionPoliza) {
		this.idModificacionPoliza = idModificacionPoliza;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDatosHijo", nullable = false)
	public DTODatosdehijo getDatosdehijo() {
		return this.dTODatosdehijo;
	}

	public void setDatosdehijo(DTODatosdehijo dTODatosdehijo) {
		this.dTODatosdehijo = dTODatosdehijo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMedidasSeguridad", nullable = false)
	public DTOMedidasdeseguridad getMedidasdeseguridad() {
		return this.dTOMedidasdeseguridad;
	}

	public void setMedidasdeseguridad(DTOMedidasdeseguridad dTOMedidasdeseguridad) {
		this.dTOMedidasdeseguridad = dTOMedidasdeseguridad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "identNroPoliza", nullable = false)
	public DTOPoliza getPoliza() {
		return this.dTOPoliza;
	}

	public void setPoliza(DTOPoliza dTOPoliza) {
		this.dTOPoliza = dTOPoliza;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoCobertura", nullable = false)
	public DTOTipocobertura getTipocobertura() {
		return this.dTOTipocobertura;
	}

	public void setTipocobertura(DTOTipocobertura dTOTipocobertura) {
		this.dTOTipocobertura = dTOTipocobertura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idVehiculo", nullable = false)
	public DTOVehiculo getVehiculo() {
		return this.dTOVehiculo;
	}

	public void setVehiculo(DTOVehiculo dTOVehiculo) {
		this.dTOVehiculo = dTOVehiculo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "anio", length = 0)
	public Date getAnio() {
		return this.anio;
	}

	public void setAnio(Date anio) {
		this.anio = anio;
	}

	@Column(name = "patente", length = 10)
	public String getPatente() {
		return this.patente;
	}

	public void setPatente(String patente) {
		this.patente = patente;
	}

	@Column(name = "motor", length = 20)
	public String getMotor() {
		return this.motor;
	}

	public void setMotor(String motor) {
		this.motor = motor;
	}

	@Column(name = "chasis", length = 20)
	public String getChasis() {
		return this.chasis;
	}

	public void setChasis(String chasis) {
		this.chasis = chasis;
	}

	@Column(name = "nroSiniestro", length = 10)
	public String getNroSiniestro() {
		return this.nroSiniestro;
	}

	public void setNroSiniestro(String nroSiniestro) {
		this.nroSiniestro = nroSiniestro;
	}

	@Column(name = "kmPorAnio")
	public Integer getKmPorAnio() {
		return this.kmPorAnio;
	}

	public void setKmPorAnio(Integer kmPorAnio) {
		this.kmPorAnio = kmPorAnio;
	}

	@Column(name = "montoTotal", precision = 12, scale = 0)
	public Float getMontoTotal() {
		return this.montoTotal;
	}

	public void setMontoTotal(Float montoTotal) {
		this.montoTotal = montoTotal;
	}

}
