package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTOModelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "dbelaseguradov4")
public class DTOModelo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idModelo;
	private DTOMarca dTOMarca;
	private String nombre;
	private Float porcentaje;
	private String modelocol;
	private Set<DTOAniomodelo> dTOAniomodelos = new HashSet<DTOAniomodelo>(0);
	private Set<DTOVehiculo> dTOVehiculos = new HashSet<DTOVehiculo>(0);

	public DTOModelo() {
	}

	public DTOModelo(DTOMarca dTOMarca) {
		this.dTOMarca = dTOMarca;
	}

	public DTOModelo(DTOMarca dTOMarca, String nombre, Float porcentaje, String modelocol, Set<DTOAniomodelo> dTOAniomodelos,
			Set<DTOVehiculo> dTOVehiculos) {
		this.dTOMarca = dTOMarca;
		this.nombre = nombre;
		this.porcentaje = porcentaje;
		this.modelocol = modelocol;
		this.dTOAniomodelos = dTOAniomodelos;
		this.dTOVehiculos = dTOVehiculos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idModelo", unique = true, nullable = false)
	public Integer getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(Integer idModelo) {
		this.idModelo = idModelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMarca", nullable = false)
	public DTOMarca getMarca() {
		return this.dTOMarca;
	}

	public void setMarca(DTOMarca dTOMarca) {
		this.dTOMarca = dTOMarca;
	}

	@Column(name = "nombre", length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "porcentaje", precision = 12, scale = 0)
	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "modelocol", length = 40)
	public String getModelocol() {
		return this.modelocol;
	}

	public void setModelocol(String modelocol) {
		this.modelocol = modelocol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<DTOAniomodelo> getAniomodelos() {
		return this.dTOAniomodelos;
	}

	public void setAniomodelos(Set<DTOAniomodelo> dTOAniomodelos) {
		this.dTOAniomodelos = dTOAniomodelos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<DTOVehiculo> getVehiculos() {
		return this.dTOVehiculos;
	}

	public void setVehiculos(Set<DTOVehiculo> dTOVehiculos) {
		this.dTOVehiculos = dTOVehiculos;
	}

}
