package ar.TpDisenio2019.DTO;
// Generated 17/11/2019 18:40:49 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DTOMarca generated by hbm2java
 */
@Entity
@Table(name = "marca", catalog = "dbelaseguradov4")
public class DTOMarca  {

	private int idMarca;
	private String marca;

	public DTOMarca() {
	}

	public DTOMarca(int idMarca) {
		this.idMarca = idMarca;
	}

	public DTOMarca(int idMarca, String marca) {
		this.idMarca = idMarca;
		this.marca = marca;
	}

	@Id

	@Column(name = "idMarca", unique = true, nullable = false)
	public int getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(int idMarca) {
		this.idMarca = idMarca;
	}

	@Column(name = "marca", length = 50)
	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

}
