package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTONumeropoliza generated by hbm2java
 */
@Entity
@Table(name = "numeropoliza", catalog = "dbelaseguradov4")
public class DTONumeropoliza implements java.io.Serializable {

	private Long nroPoliza;
	private int nroSucursal;
	private int aleatorio;
	private int secuencia;
	private Set<DTOPoliza> dTOPolizas = new HashSet<DTOPoliza>(0);

	public DTONumeropoliza() {
	}

	public DTONumeropoliza(int nroSucursal, int aleatorio, int secuencia) {
		this.nroSucursal = nroSucursal;
		this.aleatorio = aleatorio;
		this.secuencia = secuencia;
	}

	public DTONumeropoliza(int nroSucursal, int aleatorio, int secuencia, Set<DTOPoliza> dTOPolizas) {
		this.nroSucursal = nroSucursal;
		this.aleatorio = aleatorio;
		this.secuencia = secuencia;
		this.dTOPolizas = dTOPolizas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "nroPoliza", unique = true, nullable = false)
	public Long getNroPoliza() {
		return this.nroPoliza;
	}

	public void setNroPoliza(Long nroPoliza) {
		this.nroPoliza = nroPoliza;
	}

	@Column(name = "nroSucursal", nullable = false)
	public int getNroSucursal() {
		return this.nroSucursal;
	}

	public void setNroSucursal(int nroSucursal) {
		this.nroSucursal = nroSucursal;
	}

	@Column(name = "aleatorio", nullable = false)
	public int getAleatorio() {
		return this.aleatorio;
	}

	public void setAleatorio(int aleatorio) {
		this.aleatorio = aleatorio;
	}

	@Column(name = "secuencia", nullable = false)
	public int getSecuencia() {
		return this.secuencia;
	}

	public void setSecuencia(int secuencia) {
		this.secuencia = secuencia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "numeropoliza")
	public Set<DTOPoliza> getPolizas() {
		return this.dTOPolizas;
	}

	public void setPolizas(Set<DTOPoliza> dTOPolizas) {
		this.dTOPolizas = dTOPolizas;
	}

}
