package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTOOperador generated by hbm2java
 */
@Entity
@Table(name = "operador", catalog = "dbelaseguradov4")
public class DTOOperador implements java.io.Serializable {

	private Integer idOperador;
	private String nombre;
	private Set<DTORecibo> dTORecibos = new HashSet<DTORecibo>(0);

	public DTOOperador() {
	}

	public DTOOperador(String nombre, Set<DTORecibo> dTORecibos) {
		this.nombre = nombre;
		this.dTORecibos = dTORecibos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idOperador", unique = true, nullable = false)
	public Integer getIdOperador() {
		return this.idOperador;
	}

	public void setIdOperador(Integer idOperador) {
		this.idOperador = idOperador;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operador")
	public Set<DTORecibo> getRecibos() {
		return this.dTORecibos;
	}

	public void setRecibos(Set<DTORecibo> dTORecibos) {
		this.dTORecibos = dTORecibos;
	}

}
