package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DTOPoliza generated by hbm2java
 */
@Entity
@Table(name = "poliza", catalog = "dbelaseguradov4")
public class DTOPoliza implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer identNroPoliza;
	private DTOCliente dTOCliente;
	private DTOCuota dTOCuota;
	private DTODatosdehijo dTODatosdehijo;
	private DTOEstado dTOEstado;
	private DTOFactoresusados dTOFactoresusados;
	private DTOFormasdepago dTOFormasdepago;
	private DTOKmporanio dTOKmporanio;
	private DTOMedidasdeseguridad dTOMedidasdeseguridad;
	private DTONumeropoliza dTONumeropoliza;
	private DTOParametrosgenerales dTOParametrosgenerales;
	private DTOSiniestro dTOSiniestro;
	private DTOTipocobertura dTOTipocobertura;
	private DTOVehiculo dTOVehiculo;
	private Integer idEstadoCliente;
	private Date fechaInicioVigencia;
	private Date fechaFinVigencia;
	private Float sumaAsegurada;
	private String nroSiniestro;
	private Integer cantidad;
	private List<DTOCuota> listadtocuota;
	private List<DTOCuota> listadtocuotaSeleccionada;
	private Long nroPoliza;
	private float sumaTotal;
	private float recargoPorMoraAcumulado;
	 private float bonificacionAcumulado;
	
	private Set<DTOModificacionpoliza> dTOModificacionpolizas = new HashSet<DTOModificacionpoliza>(0);

	public DTOPoliza() {
	}

	public DTOPoliza(DTOCliente dTOCliente, DTOCuota dTOCuota, DTODatosdehijo dTODatosdehijo, DTOEstado dTOEstado,
			DTOFactoresusados dTOFactoresusados, DTOFormasdepago dTOFormasdepago, DTOKmporanio dTOKmporanio,
			DTOMedidasdeseguridad dTOMedidasdeseguridad, DTONumeropoliza dTONumeropoliza,
			DTOParametrosgenerales dTOParametrosgenerales, DTOSiniestro dTOSiniestro, DTOTipocobertura dTOTipocobertura,
			DTOVehiculo dTOVehiculo, Integer idEstadoCliente, Date fechaInicioVigencia, Date fechaFinVigencia,
			Float sumaAsegurada, String nroSiniestro, Integer cantidad,
			Set<DTOModificacionpoliza> dTOModificacionpolizas) {
		this.dTOCliente = dTOCliente;
		this.dTOCuota = dTOCuota;
		this.dTODatosdehijo = dTODatosdehijo;
		this.dTOEstado = dTOEstado;
		this.dTOFactoresusados = dTOFactoresusados;
		this.dTOFormasdepago = dTOFormasdepago;
		this.dTOKmporanio = dTOKmporanio;
		this.dTOMedidasdeseguridad = dTOMedidasdeseguridad;
		this.dTONumeropoliza = dTONumeropoliza;
		this.dTOParametrosgenerales = dTOParametrosgenerales;
		this.dTOSiniestro = dTOSiniestro;
		this.dTOTipocobertura = dTOTipocobertura;
		this.dTOVehiculo = dTOVehiculo;
		this.idEstadoCliente = idEstadoCliente;
		this.fechaInicioVigencia = fechaInicioVigencia;
		this.fechaFinVigencia = fechaFinVigencia;
		this.sumaAsegurada = sumaAsegurada;
		this.nroSiniestro = nroSiniestro;
		this.cantidad = cantidad;
		this.dTOModificacionpolizas = dTOModificacionpolizas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "identNroPoliza", unique = true, nullable = false)
	public Integer getIdentNroPoliza() {
		return this.identNroPoliza;
	}

	public void setIdentNroPoliza(Integer identNroPoliza) {
		this.identNroPoliza = identNroPoliza;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCliente")
	public DTOCliente getCliente() {
		return this.dTOCliente;
	}

	public void setCliente(DTOCliente dTOCliente) {
		this.dTOCliente = dTOCliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCuotas")
	public DTOCuota getCuota() {
		return this.dTOCuota;
	}

	public void setCuota(DTOCuota dTOCuota) {
		this.dTOCuota = dTOCuota;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDatosHijo")
	public DTODatosdehijo getDatosdehijo() {
		return this.dTODatosdehijo;
	}

	public void setDatosdehijo(DTODatosdehijo dTODatosdehijo) {
		this.dTODatosdehijo = dTODatosdehijo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEstado")
	public DTOEstado getEstado() {
		return this.dTOEstado;
	}

	public void setEstado(DTOEstado dTOEstado) {
		this.dTOEstado = dTOEstado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFacUsados")
	public DTOFactoresusados getFactoresusados() {
		return this.dTOFactoresusados;
	}

	public void setFactoresusados(DTOFactoresusados dTOFactoresusados) {
		this.dTOFactoresusados = dTOFactoresusados;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFormasDePago")
	public DTOFormasdepago getFormasdepago() {
		return this.dTOFormasdepago;
	}

	public void setFormasdepago(DTOFormasdepago dTOFormasdepago) {
		this.dTOFormasdepago = dTOFormasdepago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idKmPorAnio")
	public DTOKmporanio getKmporanio() {
		return this.dTOKmporanio;
	}

	public void setKmporanio(DTOKmporanio dTOKmporanio) {
		this.dTOKmporanio = dTOKmporanio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMedidasSeguridad")
	public DTOMedidasdeseguridad getMedidasdeseguridad() {
		return this.dTOMedidasdeseguridad;
	}

	public void setMedidasdeseguridad(DTOMedidasdeseguridad dTOMedidasdeseguridad) {
		this.dTOMedidasdeseguridad = dTOMedidasdeseguridad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nroPoliza")
	public DTONumeropoliza getNumeropoliza() {
		return this.dTONumeropoliza;
	}

	public void setNumeropoliza(DTONumeropoliza dTONumeropoliza) {
		this.dTONumeropoliza = dTONumeropoliza;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idParametrosGenerales")
	public DTOParametrosgenerales getParametrosgenerales() {
		return this.dTOParametrosgenerales;
	}

	public void setParametrosgenerales(DTOParametrosgenerales dTOParametrosgenerales) {
		this.dTOParametrosgenerales = dTOParametrosgenerales;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSiniestro")
	public DTOSiniestro getSiniestro() {
		return this.dTOSiniestro;
	}

	public void setSiniestro(DTOSiniestro dTOSiniestro) {
		this.dTOSiniestro = dTOSiniestro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoCobertura")
	public DTOTipocobertura getTipocobertura() {
		return this.dTOTipocobertura;
	}

	public void setTipocobertura(DTOTipocobertura dTOTipocobertura) {
		this.dTOTipocobertura = dTOTipocobertura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idVehiculo")
	public DTOVehiculo getVehiculo() {
		return this.dTOVehiculo;
	}

	public void setVehiculo(DTOVehiculo dTOVehiculo) {
		this.dTOVehiculo = dTOVehiculo;
	}

	@Column(name = "idEstadoCliente")
	public Integer getIdEstadoCliente() {
		return this.idEstadoCliente;
	}

	public void setIdEstadoCliente(Integer idEstadoCliente) {
		this.idEstadoCliente = idEstadoCliente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaInicioVigencia", length = 10)
	public Date getFechaInicioVigencia() {
		return this.fechaInicioVigencia;
	}

	public void setFechaInicioVigencia(Date fechaInicioVigencia) {
		this.fechaInicioVigencia = fechaInicioVigencia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaFinVigencia", length = 10)
	public Date getFechaFinVigencia() {
		return this.fechaFinVigencia;
	}

	public void setFechaFinVigencia(Date fechaFinVigencia) {
		this.fechaFinVigencia = fechaFinVigencia;
	}

	@Column(name = "sumaAsegurada", precision = 6)
	public Float getSumaAsegurada() {
		return this.sumaAsegurada;
	}

	public void setSumaAsegurada(Float sumaAsegurada) {
		this.sumaAsegurada = sumaAsegurada;
	}

	@Column(name = "nroSiniestro", length = 1)
	public String getNroSiniestro() {
		return this.nroSiniestro;
	}

	public void setNroSiniestro(String nroSiniestro2) {
		this.nroSiniestro = nroSiniestro2;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public List<DTOCuota> getListadtocuota() {
		return listadtocuota;
	}

	public void setListadtocuota(List<DTOCuota> listadtocuota) {
		this.listadtocuota = listadtocuota;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poliza")
	public Set<DTOModificacionpoliza> getModificacionpolizas() {
		return this.dTOModificacionpolizas;
	}

	public Long getNroPoliza() {
		return nroPoliza;
	}

	public void setNroPoliza(Long nroPoliza) {
		this.nroPoliza = nroPoliza;
	}

	public void setModificacionpolizas(Set<DTOModificacionpoliza> dTOModificacionpolizas) {
		this.dTOModificacionpolizas = dTOModificacionpolizas;
	}

	public List<DTOCuota> getListadtocuotaSeleccionada() {
		return listadtocuotaSeleccionada;
	}

	public void setListadtocuotaSeleccionada(List<DTOCuota> listadtocuotaSeleccionada) {
		this.listadtocuotaSeleccionada = listadtocuotaSeleccionada;
	}

	public float getSumaTotal() {
		return sumaTotal;
	}

	public void setSumaTotal(float sumaTotal) {
		this.sumaTotal = sumaTotal;
	}

	public float getBonificacionAcumulado() {
		return bonificacionAcumulado;
	}

	public void setBonificacionAcumulado(float bonificacionAcumulado) {
		this.bonificacionAcumulado = bonificacionAcumulado;
	}

	public float getRecargoPorMoraAcumulado() {
		return recargoPorMoraAcumulado;
	}

	public void setRecargoPorMoraAcumulado(float recargoPorMoraAcumulado) {
		this.recargoPorMoraAcumulado = recargoPorMoraAcumulado;
	}
	
	

}
