package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTOProvincia generated by hbm2java
 */
@Entity
@Table(name = "provincia", catalog = "dbelaseguradov4")
public class DTOProvincia implements java.io.Serializable {

	private Integer idProvincia;
	private DTOPais dTOPais;
	private String nombre;
	private Set<DTOLocalidad> dTOLocalidads = new HashSet<DTOLocalidad>(0);

	public DTOProvincia() {
	}

	public DTOProvincia(DTOPais dTOPais, String nombre, Set<DTOLocalidad> dTOLocalidads) {
		this.dTOPais = dTOPais;
		this.nombre = nombre;
		this.dTOLocalidads = dTOLocalidads;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idProvincia", unique = true, nullable = false)
	public Integer getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(Integer idProvincia) {
		this.idProvincia = idProvincia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPais")
	public DTOPais getPais() {
		return this.dTOPais;
	}

	public void setPais(DTOPais dTOPais) {
		this.dTOPais = dTOPais;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provincia")
	public Set<DTOLocalidad> getLocalidads() {
		return this.dTOLocalidads;
	}

	public void setLocalidads(Set<DTOLocalidad> dTOLocalidads) {
		this.dTOLocalidads = dTOLocalidads;
	}

}
