package ar.TpDisenio2019.DTO;
// Generated 17/11/2019 18:40:49 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DTOTipodedocumento generated by hbm2java
 */
@Entity
@Table(name = "tipodedocumento", catalog = "dbelaseguradov4")
public class DTOTipodedocumento  {

	private int idTipoDeDocumento;
	private String nombre;

	public DTOTipodedocumento() {
	}

	public DTOTipodedocumento(int idTipoDeDocumento) {
		this.idTipoDeDocumento = idTipoDeDocumento;
	}

	public DTOTipodedocumento(int idTipoDeDocumento, String nombre) {
		this.idTipoDeDocumento = idTipoDeDocumento;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "idTipoDeDocumento", unique = true, nullable = false)
	public int getIdTipoDeDocumento() {
		return this.idTipoDeDocumento;
	}

	public void setIdTipoDeDocumento(int idTipoDeDocumento) {
		this.idTipoDeDocumento = idTipoDeDocumento;
	}

	@Column(name = "nombre", length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
