package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTOTipocobertura generated by hbm2java
 */
@Entity
@Table(name = "tipocobertura", catalog = "dbelaseguradov4")
public class DTOTipocobertura implements java.io.Serializable {

	private Integer idTipoCobertura;
	private String tipo;
	private Float porcentaje;
	private String descripcion;
	private Set<DTOModificacionpoliza> dTOModificacionpolizas = new HashSet<DTOModificacionpoliza>(0);
	private Set<DTOPoliza> dTOPolizas = new HashSet<DTOPoliza>(0);

	public DTOTipocobertura() {
	}

	public DTOTipocobertura(String tipo, Float porcentaje, String descripcion, Set<DTOModificacionpoliza> dTOModificacionpolizas,
			Set<DTOPoliza> dTOPolizas) {
		this.tipo = tipo;
		this.porcentaje = porcentaje;
		this.descripcion = descripcion;
		this.dTOModificacionpolizas = dTOModificacionpolizas;
		this.dTOPolizas = dTOPolizas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoCobertura", unique = true, nullable = false)
	public Integer getIdTipoCobertura() {
		return this.idTipoCobertura;
	}

	public void setIdTipoCobertura(Integer idTipoCobertura) {
		this.idTipoCobertura = idTipoCobertura;
	}

	@Column(name = "tipo", length = 100)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "porcentaje", precision = 12, scale = 0)
	public Float getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Float porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipocobertura")
	public Set<DTOModificacionpoliza> getModificacionpolizas() {
		return this.dTOModificacionpolizas;
	}

	public void setModificacionpolizas(Set<DTOModificacionpoliza> dTOModificacionpolizas) {
		this.dTOModificacionpolizas = dTOModificacionpolizas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipocobertura")
	public Set<DTOPoliza> getPolizas() {
		return this.dTOPolizas;
	}

	public void setPolizas(Set<DTOPoliza> dTOPolizas) {
		this.dTOPolizas = dTOPolizas;
	}

}
