package ar.TpDisenio2019.DTO;
// Generated 19/01/2020 00:05:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DTOVehiculo generated by hbm2java
 */
@Entity
@Table(name = "vehiculo", catalog = "dbelaseguradov4")
public class DTOVehiculo implements java.io.Serializable {

	private Integer idVehiculo;
	private DTOModelo dTOModelo;
	private String motor;
	private String chasis;
	private Integer anio;
	private String patente;
	private Set<DTOModificacionpoliza> dTOModificacionpolizas = new HashSet<DTOModificacionpoliza>(0);
	private Set<DTOPoliza> dTOPolizas = new HashSet<DTOPoliza>(0);

	public DTOVehiculo() {
	}

	public DTOVehiculo(DTOModelo dTOModelo, String motor, String chasis, Integer anio, String patente,
			Set<DTOModificacionpoliza> dTOModificacionpolizas, Set<DTOPoliza> dTOPolizas) {
		this.dTOModelo = dTOModelo;
		this.motor = motor;
		this.chasis = chasis;
		this.anio = anio;
		this.patente = patente;
		this.dTOModificacionpolizas = dTOModificacionpolizas;
		this.dTOPolizas = dTOPolizas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idVehiculo", unique = true, nullable = false)
	public Integer getIdVehiculo() {
		return this.idVehiculo;
	}

	public void setIdVehiculo(Integer idVehiculo) {
		this.idVehiculo = idVehiculo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idModelo")
	public DTOModelo getModelo() {
		return this.dTOModelo;
	}

	public void setModelo(DTOModelo dTOModelo) {
		this.dTOModelo = dTOModelo;
	}

	@Column(name = "motor", length = 20)
	public String getMotor() {
		return this.motor;
	}

	public void setMotor(String motor) {
		this.motor = motor;
	}

	@Column(name = "chasis", length = 20)
	public String getChasis() {
		return this.chasis;
	}

	public void setChasis(String chasis) {
		this.chasis = chasis;
	}

	@Column(name = "anio")
	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	@Column(name = "patente", length = 10)
	public String getPatente() {
		return this.patente;
	}

	public void setPatente(String patente) {
		this.patente = patente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehiculo")
	public Set<DTOModificacionpoliza> getModificacionpolizas() {
		return this.dTOModificacionpolizas;
	}

	public void setModificacionpolizas(Set<DTOModificacionpoliza> dTOModificacionpolizas) {
		this.dTOModificacionpolizas = dTOModificacionpolizas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehiculo")
	public Set<DTOPoliza> getPolizas() {
		return this.dTOPolizas;
	}

	public void setPolizas(Set<DTOPoliza> dTOPolizas) {
		this.dTOPolizas = dTOPolizas;
	}

}
