package ar.TpDisenio2019.DTO;
// Generated 17/11/2019 18:40:49 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DTOVehiculo generated by hbm2java
 */
@Entity
@Table(name = "vehiculo", catalog = "dbelaseguradov4")
public class DTOVehiculo  {

	private int idVehiculo;
	private DTOModelo modelo;
	private String motor;
	private String chasis;
	private Integer anio;
	private String patente;

	public DTOVehiculo() {
	}

	public DTOVehiculo(int idVehiculo) {
		this.idVehiculo = idVehiculo;
	}

	public DTOVehiculo(int idVehiculo, DTOModelo idModelo, String motor, String chasis, Integer anio, String patente) {
		this.idVehiculo = idVehiculo;
		this.modelo = idModelo;
		this.motor = motor;
		this.chasis = chasis;
		this.anio = anio;
		this.patente = patente;
	}

	@Id

	@Column(name = "idVehiculo", unique = true, nullable = false)
	public int getIdVehiculo() {
		return this.idVehiculo;
	}

	public void setIdVehiculo(int idVehiculo) {
		this.idVehiculo = idVehiculo;
	}

	@Column(name = "idModelo")
	public DTOModelo getIdModelo() {
		return this.modelo;
	}

	public void setIdModelo(DTOModelo idModelo) {
		this.modelo = idModelo;
	}

	@Column(name = "motor", length = 20)
	public String getMotor() {
		return this.motor;
	}

	public void setMotor(String motor) {
		this.motor = motor;
	}

	@Column(name = "chasis", length = 20)
	public String getChasis() {
		return this.chasis;
	}

	public void setChasis(String chasis) {
		this.chasis = chasis;
	}

	@Column(name = "anio")
	public Integer getAnio() {
		return this.anio;
	}

	public void setAnio(Integer anio) {
		this.anio = anio;
	}

	@Column(name = "patente", length = 10)
	public String getPatente() {
		return this.patente;
	}

	public void setPatente(String patente) {
		this.patente = patente;
	}

}
